2022-09-15 08:51:45,112 - maincontroller.py - line:427 - INFO| [+] AGX API is running [2022-09-15 08:51:45.112585]
2022-09-15 08:55:55,378 - maincontroller.py - line:427 - INFO| [+] AGX API is running [2022-09-15 08:55:55.378461]
2022-09-15 08:56:13,706 - maincontroller.py - line:92 - INFO| obj_task
2022-09-15 08:56:29,284 - maincontroller.py - line:92 - INFO| obj_task
2022-09-15 08:56:41,425 - maincontroller.py - line:92 - INFO| obj_task
2022-09-15 09:27:35,597 - maincontroller.py - line:423 - INFO| [+] AGX API is running [2022-09-15 09:27:35.597317]
2022-09-15 09:56:03,301 - maincontroller.py - line:367 - INFO| fname: DJI_20220915095559_0001_Z.JPG,floder_name: DJI_202209150954_072_Test-Group-One,fpath: _1581F5BKD225H00BJX97_Uoto_2022-09-15/DJI_20220915095559_0001_Z.JPG,bucket_name: ytwl-jichang,
2022-09-15 09:56:03,894 - maincontroller.py - line:381 - INFO| 开始向航线数据表插入数据
2022-09-15 09:56:03,914 - maincontroller.py - line:385 - INFO| 数据插入成功
2022-09-15 09:56:03,915 - maincontroller.py - line:391 - INFO| image_url: http://124.89.8.210:3006//images/write_imgs//DJI_20220915095559_0001_Z.JPG
2022-09-15 09:56:03,922 - maincontroller.py - line:397 - INFO| 开始向任务数据表插入数据
2022-09-15 09:56:04,290 - maincontroller.py - line:408 - ERROR| 图片分析异常:Traceback (most recent call last):
  File "D:\Python38\lib\site-packages\sqlalchemy\engine\base.py", line 1277, in _execute_context
    self.dialect.do_execute(
  File "D:\Python38\lib\site-packages\sqlalchemy\engine\default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
  File "D:\Python38\lib\site-packages\mysql\connector\cursor.py", line 551, in execute
    self._handle_result(self._connection.cmd_query(stmt))
  File "D:\Python38\lib\site-packages\mysql\connector\connection.py", line 490, in cmd_query
    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))
  File "D:\Python38\lib\site-packages\mysql\connector\connection.py", line 395, in _handle_result
    raise errors.get_exception(packet)
mysql.connector.errors.IntegrityError: 1048 (23000): Column 'tag' cannot be null

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\DJI-Runway-Inspection\DJI-Runway-Inspection\server\maincontroller.py", line 402, in download_file
    db.session.commit()
  File "D:\Python38\lib\site-packages\sqlalchemy\orm\scoping.py", line 163, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "D:\Python38\lib\site-packages\sqlalchemy\orm\session.py", line 1042, in commit
    self.transaction.commit()
  File "D:\Python38\lib\site-packages\sqlalchemy\orm\session.py", line 504, in commit
    self._prepare_impl()
  File "D:\Python38\lib\site-packages\sqlalchemy\orm\session.py", line 483, in _prepare_impl
    self.session.flush()
  File "D:\Python38\lib\site-packages\sqlalchemy\orm\session.py", line 2523, in flush
    self._flush(objects)
  File "D:\Python38\lib\site-packages\sqlalchemy\orm\session.py", line 2664, in _flush
    transaction.rollback(_capture_exception=True)
  File "D:\Python38\lib\site-packages\sqlalchemy\util\langhelpers.py", line 68, in __exit__
    compat.raise_(
  File "D:\Python38\lib\site-packages\sqlalchemy\util\compat.py", line 178, in raise_
    raise exception
  File "D:\Python38\lib\site-packages\sqlalchemy\orm\session.py", line 2624, in _flush
    flush_context.execute()
  File "D:\Python38\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 422, in execute
    rec.execute(self)
  File "D:\Python38\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 586, in execute
    persistence.save_obj(
  File "D:\Python38\lib\site-packages\sqlalchemy\orm\persistence.py", line 239, in save_obj
    _emit_insert_statements(
  File "D:\Python38\lib\site-packages\sqlalchemy\orm\persistence.py", line 1135, in _emit_insert_statements
    result = cached_connections[connection].execute(
  File "D:\Python38\lib\site-packages\sqlalchemy\engine\base.py", line 1014, in execute
    return meth(self, multiparams, params)
  File "D:\Python38\lib\site-packages\sqlalchemy\sql\elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "D:\Python38\lib\site-packages\sqlalchemy\engine\base.py", line 1127, in _execute_clauseelement
    ret = self._execute_context(
  File "D:\Python38\lib\site-packages\sqlalchemy\engine\base.py", line 1317, in _execute_context
    self._handle_dbapi_exception(
  File "D:\Python38\lib\site-packages\sqlalchemy\engine\base.py", line 1511, in _handle_dbapi_exception
    util.raise_(
  File "D:\Python38\lib\site-packages\sqlalchemy\util\compat.py", line 178, in raise_
    raise exception
  File "D:\Python38\lib\site-packages\sqlalchemy\engine\base.py", line 1277, in _execute_context
    self.dialect.do_execute(
  File "D:\Python38\lib\site-packages\sqlalchemy\engine\default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
  File "D:\Python38\lib\site-packages\mysql\connector\cursor.py", line 551, in execute
    self._handle_result(self._connection.cmd_query(stmt))
  File "D:\Python38\lib\site-packages\mysql\connector\connection.py", line 490, in cmd_query
    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))
  File "D:\Python38\lib\site-packages\mysql\connector\connection.py", line 395, in _handle_result
    raise errors.get_exception(packet)
sqlalchemy.exc.IntegrityError: (mysql.connector.errors.IntegrityError) 1048 (23000): Column 'tag' cannot be null
[SQL: INSERT INTO tb_task (task_name, route_name, is_analysis, is_orimg, route_id, tag, create_time) VALUES (%(task_name)s, %(route_name)s, %(is_analysis)s, %(is_orimg)s, %(route_id)s, %(tag)s, %(create_time)s)]
[parameters: {'task_name': 'DJI_202209150954_072_Test-Group-One', 'route_name': 'Test-Group-One', 'is_analysis': '0', 'is_orimg': '0', 'route_id': 3, 'tag': None, 'create_time': datetime.datetime(2022, 9, 15, 9, 56, 3, 923795)}]
(Background on this error at: http://sqlalche.me/e/13/gkpj)
行数:402
2022-09-15 09:57:39,178 - maincontroller.py - line:367 - INFO| fname: DJI_20220915095736_0002_Z.JPG,floder_name: DJI_202209150954_072_Test-Group-One,fpath: _1581F5BKD225H00BJX97_Uoto_2022-09-15/DJI_20220915095736_0002_Z.JPG,bucket_name: ytwl-jichang,
2022-09-15 09:57:39,695 - maincontroller.py - line:391 - INFO| image_url: http://124.89.8.210:3006//images/write_imgs//DJI_20220915095736_0002_Z.JPG
2022-09-15 09:57:39,702 - maincontroller.py - line:397 - INFO| 开始向任务数据表插入数据
2022-09-15 09:57:39,710 - maincontroller.py - line:408 - ERROR| 图片分析异常:Traceback (most recent call last):
  File "D:\Python38\lib\site-packages\sqlalchemy\engine\base.py", line 1277, in _execute_context
    self.dialect.do_execute(
  File "D:\Python38\lib\site-packages\sqlalchemy\engine\default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
  File "D:\Python38\lib\site-packages\mysql\connector\cursor.py", line 551, in execute
    self._handle_result(self._connection.cmd_query(stmt))
  File "D:\Python38\lib\site-packages\mysql\connector\connection.py", line 490, in cmd_query
    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))
  File "D:\Python38\lib\site-packages\mysql\connector\connection.py", line 395, in _handle_result
    raise errors.get_exception(packet)
mysql.connector.errors.IntegrityError: 1048 (23000): Column 'tag' cannot be null

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\DJI-Runway-Inspection\DJI-Runway-Inspection\server\maincontroller.py", line 402, in download_file
    db.session.commit()
  File "D:\Python38\lib\site-packages\sqlalchemy\orm\scoping.py", line 163, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "D:\Python38\lib\site-packages\sqlalchemy\orm\session.py", line 1042, in commit
    self.transaction.commit()
  File "D:\Python38\lib\site-packages\sqlalchemy\orm\session.py", line 504, in commit
    self._prepare_impl()
  File "D:\Python38\lib\site-packages\sqlalchemy\orm\session.py", line 483, in _prepare_impl
    self.session.flush()
  File "D:\Python38\lib\site-packages\sqlalchemy\orm\session.py", line 2523, in flush
    self._flush(objects)
  File "D:\Python38\lib\site-packages\sqlalchemy\orm\session.py", line 2664, in _flush
    transaction.rollback(_capture_exception=True)
  File "D:\Python38\lib\site-packages\sqlalchemy\util\langhelpers.py", line 68, in __exit__
    compat.raise_(
  File "D:\Python38\lib\site-packages\sqlalchemy\util\compat.py", line 178, in raise_
    raise exception
  File "D:\Python38\lib\site-packages\sqlalchemy\orm\session.py", line 2624, in _flush
    flush_context.execute()
  File "D:\Python38\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 422, in execute
    rec.execute(self)
  File "D:\Python38\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 586, in execute
    persistence.save_obj(
  File "D:\Python38\lib\site-packages\sqlalchemy\orm\persistence.py", line 239, in save_obj
    _emit_insert_statements(
  File "D:\Python38\lib\site-packages\sqlalchemy\orm\persistence.py", line 1135, in _emit_insert_statements
    result = cached_connections[connection].execute(
  File "D:\Python38\lib\site-packages\sqlalchemy\engine\base.py", line 1014, in execute
    return meth(self, multiparams, params)
  File "D:\Python38\lib\site-packages\sqlalchemy\sql\elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "D:\Python38\lib\site-packages\sqlalchemy\engine\base.py", line 1127, in _execute_clauseelement
    ret = self._execute_context(
  File "D:\Python38\lib\site-packages\sqlalchemy\engine\base.py", line 1317, in _execute_context
    self._handle_dbapi_exception(
  File "D:\Python38\lib\site-packages\sqlalchemy\engine\base.py", line 1511, in _handle_dbapi_exception
    util.raise_(
  File "D:\Python38\lib\site-packages\sqlalchemy\util\compat.py", line 178, in raise_
    raise exception
  File "D:\Python38\lib\site-packages\sqlalchemy\engine\base.py", line 1277, in _execute_context
    self.dialect.do_execute(
  File "D:\Python38\lib\site-packages\sqlalchemy\engine\default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
  File "D:\Python38\lib\site-packages\mysql\connector\cursor.py", line 551, in execute
    self._handle_result(self._connection.cmd_query(stmt))
  File "D:\Python38\lib\site-packages\mysql\connector\connection.py", line 490, in cmd_query
    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))
  File "D:\Python38\lib\site-packages\mysql\connector\connection.py", line 395, in _handle_result
    raise errors.get_exception(packet)
sqlalchemy.exc.IntegrityError: (mysql.connector.errors.IntegrityError) 1048 (23000): Column 'tag' cannot be null
[SQL: INSERT INTO tb_task (task_name, route_name, is_analysis, is_orimg, route_id, tag, create_time) VALUES (%(task_name)s, %(route_name)s, %(is_analysis)s, %(is_orimg)s, %(route_id)s, %(tag)s, %(create_time)s)]
[parameters: {'task_name': 'DJI_202209150954_072_Test-Group-One', 'route_name': 'Test-Group-One', 'is_analysis': '0', 'is_orimg': '0', 'route_id': 3, 'tag': None, 'create_time': datetime.datetime(2022, 9, 15, 9, 57, 39, 703803)}]
(Background on this error at: http://sqlalche.me/e/13/gkpj)
行数:402
2022-09-15 09:58:45,348 - maincontroller.py - line:423 - INFO| [+] AGX API is running [2022-09-15 09:58:45.348422]
2022-09-15 09:58:56,350 - maincontroller.py - line:367 - INFO| fname: DJI_20220915095853_0003_Z.JPG,floder_name: DJI_202209150954_072_Test-Group-One,fpath: _1581F5BKD225H00BJX97_Uoto_2022-09-15/DJI_20220915095853_0003_Z.JPG,bucket_name: ytwl-jichang,
2022-09-15 09:58:56,906 - maincontroller.py - line:391 - INFO| image_url: http://124.89.8.210:3006//images/write_imgs//DJI_20220915095853_0003_Z.JPG
2022-09-15 09:58:56,917 - maincontroller.py - line:397 - INFO| 开始向任务数据表插入数据
2022-09-15 09:58:56,931 - maincontroller.py - line:408 - ERROR| 图片分析异常:Traceback (most recent call last):
  File "D:\Python38\lib\site-packages\sqlalchemy\engine\base.py", line 1277, in _execute_context
    self.dialect.do_execute(
  File "D:\Python38\lib\site-packages\sqlalchemy\engine\default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
  File "D:\Python38\lib\site-packages\mysql\connector\cursor.py", line 551, in execute
    self._handle_result(self._connection.cmd_query(stmt))
  File "D:\Python38\lib\site-packages\mysql\connector\connection.py", line 490, in cmd_query
    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))
  File "D:\Python38\lib\site-packages\mysql\connector\connection.py", line 395, in _handle_result
    raise errors.get_exception(packet)
mysql.connector.errors.IntegrityError: 1048 (23000): Column 'tag' cannot be null

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\DJI-Runway-Inspection\DJI-Runway-Inspection\server\maincontroller.py", line 402, in download_file
    db.session.commit()
  File "D:\Python38\lib\site-packages\sqlalchemy\orm\scoping.py", line 163, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "D:\Python38\lib\site-packages\sqlalchemy\orm\session.py", line 1042, in commit
    self.transaction.commit()
  File "D:\Python38\lib\site-packages\sqlalchemy\orm\session.py", line 504, in commit
    self._prepare_impl()
  File "D:\Python38\lib\site-packages\sqlalchemy\orm\session.py", line 483, in _prepare_impl
    self.session.flush()
  File "D:\Python38\lib\site-packages\sqlalchemy\orm\session.py", line 2523, in flush
    self._flush(objects)
  File "D:\Python38\lib\site-packages\sqlalchemy\orm\session.py", line 2664, in _flush
    transaction.rollback(_capture_exception=True)
  File "D:\Python38\lib\site-packages\sqlalchemy\util\langhelpers.py", line 68, in __exit__
    compat.raise_(
  File "D:\Python38\lib\site-packages\sqlalchemy\util\compat.py", line 178, in raise_
    raise exception
  File "D:\Python38\lib\site-packages\sqlalchemy\orm\session.py", line 2624, in _flush
    flush_context.execute()
  File "D:\Python38\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 422, in execute
    rec.execute(self)
  File "D:\Python38\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 586, in execute
    persistence.save_obj(
  File "D:\Python38\lib\site-packages\sqlalchemy\orm\persistence.py", line 239, in save_obj
    _emit_insert_statements(
  File "D:\Python38\lib\site-packages\sqlalchemy\orm\persistence.py", line 1135, in _emit_insert_statements
    result = cached_connections[connection].execute(
  File "D:\Python38\lib\site-packages\sqlalchemy\engine\base.py", line 1014, in execute
    return meth(self, multiparams, params)
  File "D:\Python38\lib\site-packages\sqlalchemy\sql\elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "D:\Python38\lib\site-packages\sqlalchemy\engine\base.py", line 1127, in _execute_clauseelement
    ret = self._execute_context(
  File "D:\Python38\lib\site-packages\sqlalchemy\engine\base.py", line 1317, in _execute_context
    self._handle_dbapi_exception(
  File "D:\Python38\lib\site-packages\sqlalchemy\engine\base.py", line 1511, in _handle_dbapi_exception
    util.raise_(
  File "D:\Python38\lib\site-packages\sqlalchemy\util\compat.py", line 178, in raise_
    raise exception
  File "D:\Python38\lib\site-packages\sqlalchemy\engine\base.py", line 1277, in _execute_context
    self.dialect.do_execute(
  File "D:\Python38\lib\site-packages\sqlalchemy\engine\default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
  File "D:\Python38\lib\site-packages\mysql\connector\cursor.py", line 551, in execute
    self._handle_result(self._connection.cmd_query(stmt))
  File "D:\Python38\lib\site-packages\mysql\connector\connection.py", line 490, in cmd_query
    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))
  File "D:\Python38\lib\site-packages\mysql\connector\connection.py", line 395, in _handle_result
    raise errors.get_exception(packet)
sqlalchemy.exc.IntegrityError: (mysql.connector.errors.IntegrityError) 1048 (23000): Column 'tag' cannot be null
[SQL: INSERT INTO tb_task (task_name, route_name, is_analysis, is_orimg, route_id, tag, create_time) VALUES (%(task_name)s, %(route_name)s, %(is_analysis)s, %(is_orimg)s, %(route_id)s, %(tag)s, %(create_time)s)]
[parameters: {'task_name': 'DJI_202209150954_072_Test-Group-One', 'route_name': 'Test-Group-One', 'is_analysis': '0', 'is_orimg': '0', 'route_id': 3, 'tag': None, 'create_time': datetime.datetime(2022, 9, 15, 9, 58, 56, 918971)}]
(Background on this error at: http://sqlalche.me/e/13/gkpj)
行数:402
2022-09-15 09:59:01,358 - maincontroller.py - line:367 - INFO| fname: DJI_20220915095858_0004_Z.JPG,floder_name: DJI_202209150954_072_Test-Group-One,fpath: _1581F5BKD225H00BJX97_Uoto_2022-09-15/DJI_20220915095858_0004_Z.JPG,bucket_name: ytwl-jichang,
2022-09-15 09:59:01,868 - maincontroller.py - line:391 - INFO| image_url: http://124.89.8.210:3006//images/write_imgs//DJI_20220915095858_0004_Z.JPG
2022-09-15 09:59:01,880 - maincontroller.py - line:397 - INFO| 开始向任务数据表插入数据
2022-09-15 09:59:01,888 - maincontroller.py - line:408 - ERROR| 图片分析异常:Traceback (most recent call last):
  File "D:\Python38\lib\site-packages\sqlalchemy\engine\base.py", line 1277, in _execute_context
    self.dialect.do_execute(
  File "D:\Python38\lib\site-packages\sqlalchemy\engine\default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
  File "D:\Python38\lib\site-packages\mysql\connector\cursor.py", line 551, in execute
    self._handle_result(self._connection.cmd_query(stmt))
  File "D:\Python38\lib\site-packages\mysql\connector\connection.py", line 490, in cmd_query
    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))
  File "D:\Python38\lib\site-packages\mysql\connector\connection.py", line 395, in _handle_result
    raise errors.get_exception(packet)
mysql.connector.errors.IntegrityError: 1048 (23000): Column 'tag' cannot be null

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\DJI-Runway-Inspection\DJI-Runway-Inspection\server\maincontroller.py", line 402, in download_file
    db.session.commit()
  File "D:\Python38\lib\site-packages\sqlalchemy\orm\scoping.py", line 163, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "D:\Python38\lib\site-packages\sqlalchemy\orm\session.py", line 1042, in commit
    self.transaction.commit()
  File "D:\Python38\lib\site-packages\sqlalchemy\orm\session.py", line 504, in commit
    self._prepare_impl()
  File "D:\Python38\lib\site-packages\sqlalchemy\orm\session.py", line 483, in _prepare_impl
    self.session.flush()
  File "D:\Python38\lib\site-packages\sqlalchemy\orm\session.py", line 2523, in flush
    self._flush(objects)
  File "D:\Python38\lib\site-packages\sqlalchemy\orm\session.py", line 2664, in _flush
    transaction.rollback(_capture_exception=True)
  File "D:\Python38\lib\site-packages\sqlalchemy\util\langhelpers.py", line 68, in __exit__
    compat.raise_(
  File "D:\Python38\lib\site-packages\sqlalchemy\util\compat.py", line 178, in raise_
    raise exception
  File "D:\Python38\lib\site-packages\sqlalchemy\orm\session.py", line 2624, in _flush
    flush_context.execute()
  File "D:\Python38\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 422, in execute
    rec.execute(self)
  File "D:\Python38\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 586, in execute
    persistence.save_obj(
  File "D:\Python38\lib\site-packages\sqlalchemy\orm\persistence.py", line 239, in save_obj
    _emit_insert_statements(
  File "D:\Python38\lib\site-packages\sqlalchemy\orm\persistence.py", line 1135, in _emit_insert_statements
    result = cached_connections[connection].execute(
  File "D:\Python38\lib\site-packages\sqlalchemy\engine\base.py", line 1014, in execute
    return meth(self, multiparams, params)
  File "D:\Python38\lib\site-packages\sqlalchemy\sql\elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "D:\Python38\lib\site-packages\sqlalchemy\engine\base.py", line 1127, in _execute_clauseelement
    ret = self._execute_context(
  File "D:\Python38\lib\site-packages\sqlalchemy\engine\base.py", line 1317, in _execute_context
    self._handle_dbapi_exception(
  File "D:\Python38\lib\site-packages\sqlalchemy\engine\base.py", line 1511, in _handle_dbapi_exception
    util.raise_(
  File "D:\Python38\lib\site-packages\sqlalchemy\util\compat.py", line 178, in raise_
    raise exception
  File "D:\Python38\lib\site-packages\sqlalchemy\engine\base.py", line 1277, in _execute_context
    self.dialect.do_execute(
  File "D:\Python38\lib\site-packages\sqlalchemy\engine\default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
  File "D:\Python38\lib\site-packages\mysql\connector\cursor.py", line 551, in execute
    self._handle_result(self._connection.cmd_query(stmt))
  File "D:\Python38\lib\site-packages\mysql\connector\connection.py", line 490, in cmd_query
    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))
  File "D:\Python38\lib\site-packages\mysql\connector\connection.py", line 395, in _handle_result
    raise errors.get_exception(packet)
sqlalchemy.exc.IntegrityError: (mysql.connector.errors.IntegrityError) 1048 (23000): Column 'tag' cannot be null
[SQL: INSERT INTO tb_task (task_name, route_name, is_analysis, is_orimg, route_id, tag, create_time) VALUES (%(task_name)s, %(route_name)s, %(is_analysis)s, %(is_orimg)s, %(route_id)s, %(tag)s, %(create_time)s)]
[parameters: {'task_name': 'DJI_202209150954_072_Test-Group-One', 'route_name': 'Test-Group-One', 'is_analysis': '0', 'is_orimg': '0', 'route_id': 3, 'tag': None, 'create_time': datetime.datetime(2022, 9, 15, 9, 59, 1, 881002)}]
(Background on this error at: http://sqlalche.me/e/13/gkpj)
行数:402
2022-09-15 09:59:19,790 - maincontroller.py - line:367 - INFO| fname: DJI_20220915095917_0005_W.JPG,floder_name: DJI_202209150954_072_Test-Group-One,fpath: _1581F5BKD225H00BJX97_Uoto_2022-09-15/DJI_20220915095917_0005_W.JPG,bucket_name: ytwl-jichang,
2022-09-15 09:59:20,314 - maincontroller.py - line:391 - INFO| image_url: http://124.89.8.210:3006//images/write_imgs//DJI_20220915095917_0005_W.JPG
2022-09-15 09:59:20,321 - maincontroller.py - line:397 - INFO| 开始向任务数据表插入数据
2022-09-15 09:59:20,328 - maincontroller.py - line:408 - ERROR| 图片分析异常:Traceback (most recent call last):
  File "D:\Python38\lib\site-packages\sqlalchemy\engine\base.py", line 1277, in _execute_context
    self.dialect.do_execute(
  File "D:\Python38\lib\site-packages\sqlalchemy\engine\default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
  File "D:\Python38\lib\site-packages\mysql\connector\cursor.py", line 551, in execute
    self._handle_result(self._connection.cmd_query(stmt))
  File "D:\Python38\lib\site-packages\mysql\connector\connection.py", line 490, in cmd_query
    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))
  File "D:\Python38\lib\site-packages\mysql\connector\connection.py", line 395, in _handle_result
    raise errors.get_exception(packet)
mysql.connector.errors.IntegrityError: 1048 (23000): Column 'tag' cannot be null

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\DJI-Runway-Inspection\DJI-Runway-Inspection\server\maincontroller.py", line 402, in download_file
    db.session.commit()
  File "D:\Python38\lib\site-packages\sqlalchemy\orm\scoping.py", line 163, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "D:\Python38\lib\site-packages\sqlalchemy\orm\session.py", line 1042, in commit
    self.transaction.commit()
  File "D:\Python38\lib\site-packages\sqlalchemy\orm\session.py", line 504, in commit
    self._prepare_impl()
  File "D:\Python38\lib\site-packages\sqlalchemy\orm\session.py", line 483, in _prepare_impl
    self.session.flush()
  File "D:\Python38\lib\site-packages\sqlalchemy\orm\session.py", line 2523, in flush
    self._flush(objects)
  File "D:\Python38\lib\site-packages\sqlalchemy\orm\session.py", line 2664, in _flush
    transaction.rollback(_capture_exception=True)
  File "D:\Python38\lib\site-packages\sqlalchemy\util\langhelpers.py", line 68, in __exit__
    compat.raise_(
  File "D:\Python38\lib\site-packages\sqlalchemy\util\compat.py", line 178, in raise_
    raise exception
  File "D:\Python38\lib\site-packages\sqlalchemy\orm\session.py", line 2624, in _flush
    flush_context.execute()
  File "D:\Python38\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 422, in execute
    rec.execute(self)
  File "D:\Python38\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 586, in execute
    persistence.save_obj(
  File "D:\Python38\lib\site-packages\sqlalchemy\orm\persistence.py", line 239, in save_obj
    _emit_insert_statements(
  File "D:\Python38\lib\site-packages\sqlalchemy\orm\persistence.py", line 1135, in _emit_insert_statements
    result = cached_connections[connection].execute(
  File "D:\Python38\lib\site-packages\sqlalchemy\engine\base.py", line 1014, in execute
    return meth(self, multiparams, params)
  File "D:\Python38\lib\site-packages\sqlalchemy\sql\elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "D:\Python38\lib\site-packages\sqlalchemy\engine\base.py", line 1127, in _execute_clauseelement
    ret = self._execute_context(
  File "D:\Python38\lib\site-packages\sqlalchemy\engine\base.py", line 1317, in _execute_context
    self._handle_dbapi_exception(
  File "D:\Python38\lib\site-packages\sqlalchemy\engine\base.py", line 1511, in _handle_dbapi_exception
    util.raise_(
  File "D:\Python38\lib\site-packages\sqlalchemy\util\compat.py", line 178, in raise_
    raise exception
  File "D:\Python38\lib\site-packages\sqlalchemy\engine\base.py", line 1277, in _execute_context
    self.dialect.do_execute(
  File "D:\Python38\lib\site-packages\sqlalchemy\engine\default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
  File "D:\Python38\lib\site-packages\mysql\connector\cursor.py", line 551, in execute
    self._handle_result(self._connection.cmd_query(stmt))
  File "D:\Python38\lib\site-packages\mysql\connector\connection.py", line 490, in cmd_query
    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))
  File "D:\Python38\lib\site-packages\mysql\connector\connection.py", line 395, in _handle_result
    raise errors.get_exception(packet)
sqlalchemy.exc.IntegrityError: (mysql.connector.errors.IntegrityError) 1048 (23000): Column 'tag' cannot be null
[SQL: INSERT INTO tb_task (task_name, route_name, is_analysis, is_orimg, route_id, tag, create_time) VALUES (%(task_name)s, %(route_name)s, %(is_analysis)s, %(is_orimg)s, %(route_id)s, %(tag)s, %(create_time)s)]
[parameters: {'task_name': 'DJI_202209150954_072_Test-Group-One', 'route_name': 'Test-Group-One', 'is_analysis': '0', 'is_orimg': '0', 'route_id': 3, 'tag': None, 'create_time': datetime.datetime(2022, 9, 15, 9, 59, 20, 322184)}]
(Background on this error at: http://sqlalche.me/e/13/gkpj)
行数:402
2022-09-15 10:00:03,492 - maincontroller.py - line:423 - INFO| [+] AGX API is running [2022-09-15 10:00:03.491954]
2022-09-15 10:01:12,040 - maincontroller.py - line:321 - INFO| image_url: http://124.89.8.210:3006/images/write_imgs/DJI_202209150954_072_Test-Group-OneDJI_20220915100108_0006_W.JPG
2022-09-15 10:01:12,048 - maincontroller.py - line:327 - INFO| 开始向任务数据表插入数据
2022-09-15 10:01:12,071 - maincontroller.py - line:333 - INFO| 任务数据插入成功
2022-09-15 10:01:12,080 - maincontroller.py - line:342 - INFO| 开始向图片表插入数据
2022-09-15 10:01:56,278 - maincontroller.py - line:89 - INFO| obj_task
2022-09-15 10:02:14,781 - maincontroller.py - line:89 - INFO| obj_task
2022-09-15 10:02:24,490 - maincontroller.py - line:321 - INFO| image_url: http://124.89.8.210:3006/images/write_imgs/DJI_202209150954_072_Test-Group-OneDJI_20220915100221_0007_W.JPG
2022-09-15 10:02:40,370 - maincontroller.py - line:89 - INFO| obj_task
2022-09-15 10:03:11,029 - maincontroller.py - line:89 - INFO| obj_task
2022-09-15 10:03:22,087 - maincontroller.py - line:342 - INFO| 开始向图片表插入数据
2022-09-15 10:03:29,065 - maincontroller.py - line:423 - INFO| [+] AGX API is running [2022-09-15 10:03:29.065428]
2022-09-15 10:03:56,022 - maincontroller.py - line:89 - INFO| obj_task
2022-09-15 10:04:10,852 - maincontroller.py - line:321 - INFO| image_url: http://124.89.8.210:3006/images/write_imgs/DJI_202209150954_072_Test-Group-One/DJI_20220915100407_0008_W.JPG
2022-09-15 10:04:10,864 - maincontroller.py - line:342 - INFO| 开始向图片表插入数据
2022-09-15 10:04:16,029 - maincontroller.py - line:89 - INFO| obj_task
2022-09-15 10:04:18,714 - maincontroller.py - line:89 - INFO| obj_task
2022-09-15 10:04:34,203 - maincontroller.py - line:321 - INFO| image_url: http://124.89.8.210:3006/images/write_imgs/DJI_202209150954_072_Test-Group-One/DJI_20220915100431_0009_W.JPG
2022-09-15 10:04:34,215 - maincontroller.py - line:342 - INFO| 开始向图片表插入数据
2022-09-15 10:04:39,403 - maincontroller.py - line:89 - INFO| obj_task
2022-09-15 10:04:40,368 - maincontroller.py - line:89 - INFO| obj_task
2022-09-15 10:04:40,935 - maincontroller.py - line:89 - INFO| obj_task
2022-09-15 10:04:41,282 - maincontroller.py - line:89 - INFO| obj_task
2022-09-15 10:04:41,710 - maincontroller.py - line:89 - INFO| obj_task
2022-09-15 10:04:46,142 - maincontroller.py - line:89 - INFO| obj_task
2022-09-15 10:04:46,736 - maincontroller.py - line:89 - INFO| obj_task
2022-09-15 10:04:47,463 - maincontroller.py - line:89 - INFO| obj_task
2022-09-15 10:04:49,370 - maincontroller.py - line:89 - INFO| obj_task
2022-09-15 10:04:53,910 - maincontroller.py - line:89 - INFO| obj_task
2022-09-15 10:05:11,471 - maincontroller.py - line:89 - INFO| obj_task
2022-09-15 10:05:20,088 - maincontroller.py - line:89 - INFO| obj_task
2022-09-15 10:05:41,178 - maincontroller.py - line:89 - INFO| obj_task
2022-09-15 10:05:46,302 - maincontroller.py - line:89 - INFO| obj_task
2022-09-15 10:05:56,899 - maincontroller.py - line:89 - INFO| obj_task
2022-09-15 10:06:55,981 - maincontroller.py - line:89 - INFO| obj_task
2022-09-15 10:07:09,514 - maincontroller.py - line:89 - INFO| obj_task
2022-09-15 10:07:38,372 - maincontroller.py - line:89 - INFO| obj_task
2022-09-15 10:08:22,882 - maincontroller.py - line:89 - INFO| obj_task
2022-09-15 10:08:25,133 - maincontroller.py - line:89 - INFO| obj_task
2022-09-15 10:08:27,080 - maincontroller.py - line:89 - INFO| obj_task
2022-09-15 10:08:30,338 - maincontroller.py - line:89 - INFO| obj_task
2022-09-15 10:08:35,625 - maincontroller.py - line:89 - INFO| obj_task
2022-09-15 10:08:37,166 - maincontroller.py - line:89 - INFO| obj_task
2022-09-15 10:08:41,947 - maincontroller.py - line:89 - INFO| obj_task
2022-09-15 10:08:41,987 - maincontroller.py - line:89 - INFO| obj_task
2022-09-15 10:08:43,247 - maincontroller.py - line:89 - INFO| obj_task
2022-09-15 10:08:53,550 - maincontroller.py - line:89 - INFO| obj_task
2022-09-15 10:09:05,255 - maincontroller.py - line:89 - INFO| obj_task
2022-09-15 10:09:05,795 - maincontroller.py - line:89 - INFO| obj_task
2022-09-15 10:09:08,977 - maincontroller.py - line:89 - INFO| obj_task
2022-09-15 10:09:14,411 - maincontroller.py - line:89 - INFO| obj_task
2022-09-15 10:09:18,851 - maincontroller.py - line:89 - INFO| obj_task
2022-09-15 10:09:19,153 - maincontroller.py - line:89 - INFO| obj_task
2022-09-15 10:09:21,522 - maincontroller.py - line:89 - INFO| obj_task
2022-09-15 10:09:24,415 - maincontroller.py - line:89 - INFO| obj_task
2022-09-15 10:10:59,824 - maincontroller.py - line:89 - INFO| obj_task
2022-09-15 10:11:12,716 - maincontroller.py - line:233 - INFO| type(task_id): <class 'int'>
2022-09-15 10:11:12,723 - maincontroller.py - line:276 - INFO| 文件夹对比成功
2022-09-15 10:11:24,275 - maincontroller.py - line:233 - INFO| type(task_id): <class 'int'>
2022-09-15 10:11:24,282 - maincontroller.py - line:276 - INFO| 文件夹对比成功
2022-09-15 10:11:43,118 - maincontroller.py - line:89 - INFO| obj_task
2022-09-15 10:11:49,817 - maincontroller.py - line:89 - INFO| obj_task
2022-09-15 10:12:02,299 - maincontroller.py - line:89 - INFO| obj_task
2022-09-15 10:12:10,739 - maincontroller.py - line:89 - INFO| obj_task
2022-09-15 10:12:17,683 - maincontroller.py - line:89 - INFO| obj_task
2022-09-15 10:12:40,202 - maincontroller.py - line:89 - INFO| obj_task
2022-09-15 10:12:49,444 - maincontroller.py - line:89 - INFO| obj_task
2022-09-15 10:13:03,205 - maincontroller.py - line:89 - INFO| obj_task
2022-09-15 10:13:16,227 - maincontroller.py - line:216 - INFO| 指定任务为模板成功!
2022-09-15 10:13:23,907 - maincontroller.py - line:233 - INFO| type(task_id): <class 'int'>
2022-09-15 10:13:23,918 - maincontroller.py - line:245 - INFO| 开始修改对比状态
2022-09-15 10:13:23,935 - maincontroller.py - line:248 - INFO| 对比状态修改成功
2022-09-15 10:13:23,984 - maincontroller.py - line:258 - INFO| 对比状态修改成功
2022-09-15 10:13:24,670 - readImageTools.py - line:45 - INFO| (3000, 4000, 3)
2022-09-15 10:13:26,284 - readImageTools.py - line:45 - INFO| (3000, 4000, 3)
2022-09-15 10:13:27,158 - timeTools.py - line:6 - INFO| 图片分析 -- 开始执行base64->rgb数组 2022-09-15 10:13:27.157742
2022-09-15 10:13:28,514 - timeTools.py - line:6 - INFO| 图片分析 -- 开始执行 uint8  2022-09-15 10:13:28.514729
2022-09-15 10:13:28,515 - timeTools.py - line:6 - INFO| 图片分析 --  开始执行差分运算  2022-09-15 10:13:28.515740
2022-09-15 10:13:39,356 - timeTools.py - line:6 - INFO| 图片分析 --  开始执行阈值分割  2022-09-15 10:13:39.356771
2022-09-15 10:13:39,372 - timeTools.py - line:6 - INFO| 图片分析 --  开始执行 开运算  2022-09-15 10:13:39.371738
2022-09-15 10:13:44,660 - maincontroller.py - line:364 - INFO| [+] AGX API is running [2022-09-15 10:13:44.660717]
2022-09-15 10:13:44,767 - maincontroller.py - line:364 - INFO| [+] AGX API is running [2022-09-15 10:13:44.767718]
2022-09-15 10:13:44,963 - maincontroller.py - line:364 - INFO| [+] AGX API is running [2022-09-15 10:13:44.963717]
2022-09-15 10:13:45,053 - maincontroller.py - line:364 - INFO| [+] AGX API is running [2022-09-15 10:13:45.053717]
2022-09-15 10:13:45,117 - maincontroller.py - line:364 - INFO| [+] AGX API is running [2022-09-15 10:13:45.116717]
2022-09-15 10:13:45,251 - maincontroller.py - line:364 - INFO| [+] AGX API is running [2022-09-15 10:13:45.251717]
2022-09-15 10:13:45,319 - maincontroller.py - line:364 - INFO| [+] AGX API is running [2022-09-15 10:13:45.319716]
2022-09-15 10:13:45,412 - maincontroller.py - line:364 - INFO| [+] AGX API is running [2022-09-15 10:13:45.411714]
2022-09-15 10:13:45,455 - maincontroller.py - line:364 - INFO| [+] AGX API is running [2022-09-15 10:13:45.455713]
2022-09-15 10:13:45,455 - maincontroller.py - line:364 - INFO| [+] AGX API is running [2022-09-15 10:13:45.455713]
2022-09-15 10:13:46,232 - maincontroller.py - line:364 - INFO| [+] AGX API is running [2022-09-15 10:13:46.232717]
2022-09-15 10:13:46,236 - maincontroller.py - line:364 - INFO| [+] AGX API is running [2022-09-15 10:13:46.236717]
2022-09-15 10:13:46,249 - maincontroller.py - line:364 - INFO| [+] AGX API is running [2022-09-15 10:13:46.249717]
2022-09-15 10:13:46,258 - maincontroller.py - line:364 - INFO| [+] AGX API is running [2022-09-15 10:13:46.258717]
2022-09-15 10:13:46,409 - maincontroller.py - line:364 - INFO| [+] AGX API is running [2022-09-15 10:13:46.409715]
2022-09-15 10:13:46,554 - maincontroller.py - line:364 - INFO| [+] AGX API is running [2022-09-15 10:13:46.554713]
2022-09-15 10:13:46,985 - detect.py - line:121 - INFO| 
2022-09-15 10:13:46,991 - timeTools.py - line:6 - INFO| 结束时间 2022-09-15 10:13:46.991714
2022-09-15 10:13:48,218 - readImageTools.py - line:45 - INFO| (3000, 4000, 3)
2022-09-15 10:13:49,253 - readImageTools.py - line:45 - INFO| (3000, 4000, 3)
2022-09-15 10:13:50,244 - timeTools.py - line:6 - INFO| 图片分析 -- 开始执行base64->rgb数组 2022-09-15 10:13:50.244732
2022-09-15 10:13:51,524 - timeTools.py - line:6 - INFO| 图片分析 -- 开始执行 uint8  2022-09-15 10:13:51.523748
2022-09-15 10:13:51,525 - timeTools.py - line:6 - INFO| 图片分析 --  开始执行差分运算  2022-09-15 10:13:51.525730
2022-09-15 10:14:03,706 - timeTools.py - line:6 - INFO| 图片分析 --  开始执行阈值分割  2022-09-15 10:14:03.706744
2022-09-15 10:14:03,721 - timeTools.py - line:6 - INFO| 图片分析 --  开始执行 开运算  2022-09-15 10:14:03.721733
2022-09-15 10:14:08,544 - maincontroller.py - line:364 - INFO| [+] AGX API is running [2022-09-15 10:14:08.544719]
2022-09-15 10:14:08,650 - maincontroller.py - line:364 - INFO| [+] AGX API is running [2022-09-15 10:14:08.650719]
2022-09-15 10:14:08,962 - maincontroller.py - line:364 - INFO| [+] AGX API is running [2022-09-15 10:14:08.962719]
2022-09-15 10:14:09,081 - maincontroller.py - line:364 - INFO| [+] AGX API is running [2022-09-15 10:14:09.081719]
2022-09-15 10:14:09,109 - maincontroller.py - line:364 - INFO| [+] AGX API is running [2022-09-15 10:14:09.109717]
2022-09-15 10:14:09,305 - maincontroller.py - line:364 - INFO| [+] AGX API is running [2022-09-15 10:14:09.305719]
2022-09-15 10:14:09,340 - maincontroller.py - line:364 - INFO| [+] AGX API is running [2022-09-15 10:14:09.340720]
2022-09-15 10:14:09,390 - maincontroller.py - line:364 - INFO| [+] AGX API is running [2022-09-15 10:14:09.390721]
2022-09-15 10:14:09,461 - maincontroller.py - line:364 - INFO| [+] AGX API is running [2022-09-15 10:14:09.460715]
2022-09-15 10:14:09,770 - maincontroller.py - line:364 - INFO| [+] AGX API is running [2022-09-15 10:14:09.770720]
2022-09-15 10:14:10,278 - maincontroller.py - line:364 - INFO| [+] AGX API is running [2022-09-15 10:14:10.278720]
2022-09-15 10:14:10,283 - maincontroller.py - line:364 - INFO| [+] AGX API is running [2022-09-15 10:14:10.283720]
2022-09-15 10:14:10,283 - maincontroller.py - line:364 - INFO| [+] AGX API is running [2022-09-15 10:14:10.283720]
2022-09-15 10:14:10,516 - maincontroller.py - line:364 - INFO| [+] AGX API is running [2022-09-15 10:14:10.516720]
2022-09-15 10:14:10,899 - detect.py - line:121 - INFO| 
2022-09-15 10:14:10,905 - timeTools.py - line:6 - INFO| 结束时间 2022-09-15 10:14:10.904716
2022-09-15 10:14:11,507 - maincontroller.py - line:364 - INFO| [+] AGX API is running [2022-09-15 10:14:11.507719]
2022-09-15 10:14:11,555 - maincontroller.py - line:364 - INFO| [+] AGX API is running [2022-09-15 10:14:11.555721]
2022-09-15 10:14:12,177 - readImageTools.py - line:45 - INFO| (3000, 4000, 3)
2022-09-15 10:14:12,831 - readImageTools.py - line:45 - INFO| (3000, 4000, 3)
2022-09-15 10:14:13,628 - timeTools.py - line:6 - INFO| 图片分析 -- 开始执行base64->rgb数组 2022-09-15 10:14:13.628743
2022-09-15 10:14:14,513 - timeTools.py - line:6 - INFO| 图片分析 -- 开始执行 uint8  2022-09-15 10:14:14.513776
2022-09-15 10:14:14,514 - timeTools.py - line:6 - INFO| 图片分析 --  开始执行差分运算  2022-09-15 10:14:14.514756
2022-09-15 10:14:25,970 - timeTools.py - line:6 - INFO| 图片分析 --  开始执行阈值分割  2022-09-15 10:14:25.970396
2022-09-15 10:14:25,987 - timeTools.py - line:6 - INFO| 图片分析 --  开始执行 开运算  2022-09-15 10:14:25.987375
2022-09-15 10:14:29,960 - maincontroller.py - line:89 - INFO| obj_task
2022-09-15 10:14:30,790 - maincontroller.py - line:364 - INFO| [+] AGX API is running [2022-09-15 10:14:30.790355]
2022-09-15 10:14:30,906 - maincontroller.py - line:364 - INFO| [+] AGX API is running [2022-09-15 10:14:30.906357]
2022-09-15 10:14:30,958 - maincontroller.py - line:364 - INFO| [+] AGX API is running [2022-09-15 10:14:30.958357]
2022-09-15 10:14:31,115 - maincontroller.py - line:364 - INFO| [+] AGX API is running [2022-09-15 10:14:31.115357]
2022-09-15 10:14:31,345 - maincontroller.py - line:364 - INFO| [+] AGX API is running [2022-09-15 10:14:31.345357]
2022-09-15 10:14:31,482 - maincontroller.py - line:364 - INFO| [+] AGX API is running [2022-09-15 10:14:31.481358]
2022-09-15 10:14:31,523 - maincontroller.py - line:364 - INFO| [+] AGX API is running [2022-09-15 10:14:31.523357]
2022-09-15 10:14:31,706 - maincontroller.py - line:364 - INFO| [+] AGX API is running [2022-09-15 10:14:31.706358]
2022-09-15 10:14:31,706 - maincontroller.py - line:364 - INFO| [+] AGX API is running [2022-09-15 10:14:31.706358]
2022-09-15 10:14:31,751 - maincontroller.py - line:364 - INFO| [+] AGX API is running [2022-09-15 10:14:31.750357]
2022-09-15 10:14:31,880 - maincontroller.py - line:364 - INFO| [+] AGX API is running [2022-09-15 10:14:31.880355]
2022-09-15 10:14:32,052 - maincontroller.py - line:364 - INFO| [+] AGX API is running [2022-09-15 10:14:32.052357]
2022-09-15 10:14:32,605 - maincontroller.py - line:364 - INFO| [+] AGX API is running [2022-09-15 10:14:32.605357]
2022-09-15 10:14:32,674 - maincontroller.py - line:364 - INFO| [+] AGX API is running [2022-09-15 10:14:32.674353]
2022-09-15 10:14:32,927 - maincontroller.py - line:364 - INFO| [+] AGX API is running [2022-09-15 10:14:32.926358]
2022-09-15 10:14:33,128 - detect.py - line:121 - INFO| 
2022-09-15 10:14:33,233 - timeTools.py - line:6 - INFO| 结束时间 2022-09-15 10:14:33.233362
2022-09-15 10:14:33,445 - maincontroller.py - line:364 - INFO| [+] AGX API is running [2022-09-15 10:14:33.445359]
2022-09-15 10:15:23,884 - maincontroller.py - line:233 - INFO| type(task_id): <class 'int'>
2022-09-15 10:15:23,896 - maincontroller.py - line:245 - INFO| 开始修改对比状态
2022-09-15 10:15:23,917 - maincontroller.py - line:248 - INFO| 对比状态修改成功
2022-09-15 10:15:23,954 - maincontroller.py - line:258 - INFO| 对比状态修改成功
2022-09-15 10:15:24,655 - readImageTools.py - line:45 - INFO| (3000, 4000, 3)
2022-09-15 10:15:26,031 - readImageTools.py - line:45 - INFO| (3000, 4000, 3)
2022-09-15 10:15:26,847 - timeTools.py - line:6 - INFO| 图片分析 -- 开始执行base64->rgb数组 2022-09-15 10:15:26.847989
2022-09-15 10:15:27,844 - timeTools.py - line:6 - INFO| 图片分析 -- 开始执行 uint8  2022-09-15 10:15:27.844991
2022-09-15 10:15:27,845 - timeTools.py - line:6 - INFO| 图片分析 --  开始执行差分运算  2022-09-15 10:15:27.845993
2022-09-15 10:15:39,037 - timeTools.py - line:6 - INFO| 图片分析 --  开始执行阈值分割  2022-09-15 10:15:39.037827
2022-09-15 10:16:28,921 - maincontroller.py - line:89 - INFO| obj_task
2022-09-15 10:16:40,945 - maincontroller.py - line:89 - INFO| obj_task
2022-09-15 10:16:43,100 - maincontroller.py - line:89 - INFO| obj_task
2022-09-15 10:16:53,308 - maincontroller.py - line:89 - INFO| obj_task
2022-09-15 10:17:04,664 - maincontroller.py - line:89 - INFO| obj_task
2022-09-15 10:17:09,893 - maincontroller.py - line:89 - INFO| obj_task
2022-09-15 10:17:36,037 - maincontroller.py - line:89 - INFO| obj_task
2022-09-15 10:18:11,058 - maincontroller.py - line:89 - INFO| obj_task
2022-09-15 10:18:34,168 - timeTools.py - line:6 - INFO| 图片分析 --  开始执行 开运算  2022-09-15 10:18:34.168194
2022-09-15 10:18:39,338 - maincontroller.py - line:364 - INFO| [+] AGX API is running [2022-09-15 10:18:39.338179]
2022-09-15 10:18:39,410 - maincontroller.py - line:364 - INFO| [+] AGX API is running [2022-09-15 10:18:39.410177]
2022-09-15 10:18:39,641 - maincontroller.py - line:364 - INFO| [+] AGX API is running [2022-09-15 10:18:39.641179]
2022-09-15 10:18:39,741 - maincontroller.py - line:364 - INFO| [+] AGX API is running [2022-09-15 10:18:39.741178]
2022-09-15 10:18:39,869 - maincontroller.py - line:364 - INFO| [+] AGX API is running [2022-09-15 10:18:39.869178]
2022-09-15 10:18:39,978 - maincontroller.py - line:364 - INFO| [+] AGX API is running [2022-09-15 10:18:39.978178]
2022-09-15 10:18:40,023 - maincontroller.py - line:364 - INFO| [+] AGX API is running [2022-09-15 10:18:40.023176]
2022-09-15 10:18:40,049 - maincontroller.py - line:364 - INFO| [+] AGX API is running [2022-09-15 10:18:40.049176]
2022-09-15 10:18:40,287 - maincontroller.py - line:364 - INFO| [+] AGX API is running [2022-09-15 10:18:40.287179]
2022-09-15 10:18:40,450 - maincontroller.py - line:364 - INFO| [+] AGX API is running [2022-09-15 10:18:40.449175]
2022-09-15 10:18:40,557 - maincontroller.py - line:364 - INFO| [+] AGX API is running [2022-09-15 10:18:40.557175]
2022-09-15 10:18:40,635 - maincontroller.py - line:364 - INFO| [+] AGX API is running [2022-09-15 10:18:40.635178]
2022-09-15 10:18:40,790 - maincontroller.py - line:364 - INFO| [+] AGX API is running [2022-09-15 10:18:40.790178]
2022-09-15 10:18:41,043 - maincontroller.py - line:364 - INFO| [+] AGX API is running [2022-09-15 10:18:41.043178]
2022-09-15 10:18:41,274 - maincontroller.py - line:364 - INFO| [+] AGX API is running [2022-09-15 10:18:41.274176]
2022-09-15 10:18:41,599 - detect.py - line:121 - INFO| 
2022-09-15 10:18:41,605 - timeTools.py - line:6 - INFO| 结束时间 2022-09-15 10:18:41.605178
2022-09-15 10:18:42,847 - readImageTools.py - line:45 - INFO| (3000, 4000, 3)
2022-09-15 10:18:43,364 - maincontroller.py - line:364 - INFO| [+] AGX API is running [2022-09-15 10:18:43.364175]
2022-09-15 10:18:43,596 - readImageTools.py - line:45 - INFO| (3000, 4000, 3)
2022-09-15 10:18:44,403 - timeTools.py - line:6 - INFO| 图片分析 -- 开始执行base64->rgb数组 2022-09-15 10:18:44.403197
2022-09-15 10:18:45,666 - timeTools.py - line:6 - INFO| 图片分析 -- 开始执行 uint8  2022-09-15 10:18:45.666192
2022-09-15 10:18:45,667 - timeTools.py - line:6 - INFO| 图片分析 --  开始执行差分运算  2022-09-15 10:18:45.667191
2022-09-15 10:18:58,378 - timeTools.py - line:6 - INFO| 图片分析 --  开始执行阈值分割  2022-09-15 10:18:58.378203
2022-09-15 10:18:58,393 - timeTools.py - line:6 - INFO| 图片分析 --  开始执行 开运算  2022-09-15 10:18:58.393202
2022-09-15 10:19:03,551 - maincontroller.py - line:364 - INFO| [+] AGX API is running [2022-09-15 10:19:03.551181]
2022-09-15 10:19:03,700 - maincontroller.py - line:364 - INFO| [+] AGX API is running [2022-09-15 10:19:03.700180]
2022-09-15 10:19:03,704 - maincontroller.py - line:364 - INFO| [+] AGX API is running [2022-09-15 10:19:03.704181]
2022-09-15 10:19:03,869 - maincontroller.py - line:364 - INFO| [+] AGX API is running [2022-09-15 10:19:03.869180]
2022-09-15 10:19:03,914 - maincontroller.py - line:364 - INFO| [+] AGX API is running [2022-09-15 10:19:03.914181]
2022-09-15 10:19:04,192 - maincontroller.py - line:364 - INFO| [+] AGX API is running [2022-09-15 10:19:04.192182]
2022-09-15 10:19:04,303 - maincontroller.py - line:364 - INFO| [+] AGX API is running [2022-09-15 10:19:04.303181]
2022-09-15 10:19:04,341 - maincontroller.py - line:364 - INFO| [+] AGX API is running [2022-09-15 10:19:04.341181]
2022-09-15 10:19:04,535 - maincontroller.py - line:364 - INFO| [+] AGX API is running [2022-09-15 10:19:04.535181]
2022-09-15 10:19:04,669 - maincontroller.py - line:364 - INFO| [+] AGX API is running [2022-09-15 10:19:04.669181]
2022-09-15 10:19:04,852 - maincontroller.py - line:364 - INFO| [+] AGX API is running [2022-09-15 10:19:04.852183]
2022-09-15 10:19:05,183 - maincontroller.py - line:364 - INFO| [+] AGX API is running [2022-09-15 10:19:05.183179]
2022-09-15 10:19:05,294 - maincontroller.py - line:364 - INFO| [+] AGX API is running [2022-09-15 10:19:05.294180]
2022-09-15 10:19:05,956 - maincontroller.py - line:364 - INFO| [+] AGX API is running [2022-09-15 10:19:05.956181]
2022-09-15 10:19:05,972 - maincontroller.py - line:364 - INFO| [+] AGX API is running [2022-09-15 10:19:05.972179]
2022-09-15 10:19:05,999 - detect.py - line:121 - INFO| 
2022-09-15 10:19:06,041 - timeTools.py - line:6 - INFO| 结束时间 2022-09-15 10:19:06.041180
2022-09-15 10:19:06,391 - maincontroller.py - line:364 - INFO| [+] AGX API is running [2022-09-15 10:19:06.391188]
2022-09-15 10:19:07,383 - readImageTools.py - line:45 - INFO| (3000, 4000, 3)
2022-09-15 10:19:07,965 - readImageTools.py - line:45 - INFO| (3000, 4000, 3)
2022-09-15 10:19:09,462 - timeTools.py - line:6 - INFO| 图片分析 -- 开始执行base64->rgb数组 2022-09-15 10:19:09.462801
2022-09-15 10:19:10,339 - timeTools.py - line:6 - INFO| 图片分析 -- 开始执行 uint8  2022-09-15 10:19:10.339803
2022-09-15 10:19:10,340 - timeTools.py - line:6 - INFO| 图片分析 --  开始执行差分运算  2022-09-15 10:19:10.340801
2022-09-15 10:19:21,887 - timeTools.py - line:6 - INFO| 图片分析 --  开始执行阈值分割  2022-09-15 10:19:21.887993
2022-09-15 10:19:50,153 - maincontroller.py - line:89 - INFO| obj_task
2022-09-15 10:19:59,978 - maincontroller.py - line:89 - INFO| obj_task
2022-09-15 10:20:07,505 - timeTools.py - line:6 - INFO| 图片分析 --  开始执行 开运算  2022-09-15 10:20:07.505004
2022-09-15 10:20:12,812 - maincontroller.py - line:364 - INFO| [+] AGX API is running [2022-09-15 10:20:12.812983]
2022-09-15 10:20:13,003 - maincontroller.py - line:364 - INFO| [+] AGX API is running [2022-09-15 10:20:13.003983]
2022-09-15 10:20:13,016 - maincontroller.py - line:364 - INFO| [+] AGX API is running [2022-09-15 10:20:13.016982]
2022-09-15 10:20:13,170 - maincontroller.py - line:364 - INFO| [+] AGX API is running [2022-09-15 10:20:13.170984]
2022-09-15 10:20:13,240 - maincontroller.py - line:364 - INFO| [+] AGX API is running [2022-09-15 10:20:13.240982]
2022-09-15 10:20:13,720 - maincontroller.py - line:364 - INFO| [+] AGX API is running [2022-09-15 10:20:13.720983]
2022-09-15 10:20:13,991 - maincontroller.py - line:364 - INFO| [+] AGX API is running [2022-09-15 10:20:13.991983]
2022-09-15 10:20:14,010 - maincontroller.py - line:364 - INFO| [+] AGX API is running [2022-09-15 10:20:14.010984]
2022-09-15 10:20:14,013 - maincontroller.py - line:364 - INFO| [+] AGX API is running [2022-09-15 10:20:14.013984]
2022-09-15 10:20:14,015 - maincontroller.py - line:364 - INFO| [+] AGX API is running [2022-09-15 10:20:14.015983]
2022-09-15 10:20:14,144 - maincontroller.py - line:364 - INFO| [+] AGX API is running [2022-09-15 10:20:14.144983]
2022-09-15 10:20:14,397 - maincontroller.py - line:364 - INFO| [+] AGX API is running [2022-09-15 10:20:14.397984]
2022-09-15 10:20:14,398 - maincontroller.py - line:364 - INFO| [+] AGX API is running [2022-09-15 10:20:14.398984]
2022-09-15 10:20:14,643 - maincontroller.py - line:364 - INFO| [+] AGX API is running [2022-09-15 10:20:14.643984]
2022-09-15 10:20:14,904 - maincontroller.py - line:364 - INFO| [+] AGX API is running [2022-09-15 10:20:14.904984]
2022-09-15 10:20:14,951 - maincontroller.py - line:364 - INFO| [+] AGX API is running [2022-09-15 10:20:14.951981]
2022-09-15 10:20:15,587 - detect.py - line:121 - INFO| 
2022-09-15 10:20:15,595 - timeTools.py - line:6 - INFO| 结束时间 2022-09-15 10:20:15.595981
2022-09-15 10:20:16,076 - maincontroller.py - line:89 - INFO| obj_task
2022-09-15 10:23:17,182 - maincontroller.py - line:321 - INFO| image_url: http://124.89.8.210:3006/images/write_imgs/DJI_202209150954_072_Test-Group-One/DJI_20220915102314_0010_W.JPG
2022-09-15 10:23:17,194 - maincontroller.py - line:342 - INFO| 开始向图片表插入数据
2022-09-15 10:23:19,946 - maincontroller.py - line:321 - INFO| image_url: http://124.89.8.210:3006/images/write_imgs/DJI_202209150954_072_Test-Group-One/DJI_20220915102316_0012_W.JPG
2022-09-15 10:23:19,958 - maincontroller.py - line:342 - INFO| 开始向图片表插入数据
2022-09-15 10:23:22,062 - maincontroller.py - line:321 - INFO| image_url: http://124.89.8.210:3006/images/write_imgs/DJI_202209150954_072_Test-Group-One/DJI_20220915102318_0013_W.JPG
2022-09-15 10:23:22,074 - maincontroller.py - line:342 - INFO| 开始向图片表插入数据
2022-09-15 10:23:24,020 - maincontroller.py - line:321 - INFO| image_url: http://124.89.8.210:3006/images/write_imgs/DJI_202209150954_072_Test-Group-One/DJI_20220915102320_0014_W.JPG
2022-09-15 10:23:24,032 - maincontroller.py - line:342 - INFO| 开始向图片表插入数据
2022-09-15 10:23:29,390 - maincontroller.py - line:89 - INFO| obj_task
2022-09-15 10:23:38,979 - maincontroller.py - line:89 - INFO| obj_task
2022-09-15 10:25:17,759 - maincontroller.py - line:89 - INFO| obj_task
2022-09-15 10:25:35,818 - maincontroller.py - line:89 - INFO| obj_task
2022-09-15 10:25:43,515 - maincontroller.py - line:89 - INFO| obj_task
2022-09-15 10:26:04,463 - maincontroller.py - line:89 - INFO| obj_task
2022-09-15 10:26:15,834 - maincontroller.py - line:321 - INFO| image_url: http://124.89.8.210:3006/images/write_imgs/DJI_202209150954_072_Test-Group-One/DJI_20220915102612_0015_W.JPG
2022-09-15 10:26:15,846 - maincontroller.py - line:342 - INFO| 开始向图片表插入数据
2022-09-15 10:26:19,826 - maincontroller.py - line:89 - INFO| obj_task
2022-09-15 10:26:36,028 - maincontroller.py - line:89 - INFO| obj_task
2022-09-15 10:28:29,968 - maincontroller.py - line:233 - INFO| type(task_id): <class 'int'>
2022-09-15 10:28:29,980 - maincontroller.py - line:245 - INFO| 开始修改对比状态
2022-09-15 10:28:29,987 - maincontroller.py - line:248 - INFO| 对比状态修改成功
2022-09-15 10:28:30,031 - maincontroller.py - line:258 - INFO| 对比状态修改成功
2022-09-15 10:28:30,720 - readImageTools.py - line:45 - INFO| (3000, 4000, 3)
2022-09-15 10:28:31,653 - readImageTools.py - line:45 - INFO| (3000, 4000, 3)
2022-09-15 10:28:31,996 - timeTools.py - line:6 - INFO| 图片分析 -- 开始执行base64->rgb数组 2022-09-15 10:28:31.996240
2022-09-15 10:28:32,445 - timeTools.py - line:6 - INFO| 图片分析 -- 开始执行 uint8  2022-09-15 10:28:32.445239
2022-09-15 10:28:32,446 - timeTools.py - line:6 - INFO| 图片分析 --  开始执行差分运算  2022-09-15 10:28:32.446239
2022-09-15 10:28:42,009 - timeTools.py - line:6 - INFO| 图片分析 --  开始执行阈值分割  2022-09-15 10:28:42.009259
2022-09-15 10:28:42,024 - timeTools.py - line:6 - INFO| 图片分析 --  开始执行 开运算  2022-09-15 10:28:42.024256
2022-09-15 10:28:47,259 - maincontroller.py - line:364 - INFO| [+] AGX API is running [2022-09-15 10:28:47.259244]
2022-09-15 10:28:47,330 - maincontroller.py - line:364 - INFO| [+] AGX API is running [2022-09-15 10:28:47.330245]
2022-09-15 10:28:47,388 - maincontroller.py - line:364 - INFO| [+] AGX API is running [2022-09-15 10:28:47.388246]
2022-09-15 10:28:47,424 - maincontroller.py - line:364 - INFO| [+] AGX API is running [2022-09-15 10:28:47.424244]
2022-09-15 10:28:47,847 - maincontroller.py - line:364 - INFO| [+] AGX API is running [2022-09-15 10:28:47.846244]
2022-09-15 10:28:48,049 - maincontroller.py - line:364 - INFO| [+] AGX API is running [2022-09-15 10:28:48.049243]
2022-09-15 10:28:48,100 - maincontroller.py - line:364 - INFO| [+] AGX API is running [2022-09-15 10:28:48.100245]
2022-09-15 10:28:48,130 - maincontroller.py - line:364 - INFO| [+] AGX API is running [2022-09-15 10:28:48.130244]
2022-09-15 10:28:48,156 - maincontroller.py - line:364 - INFO| [+] AGX API is running [2022-09-15 10:28:48.156245]
2022-09-15 10:28:48,547 - maincontroller.py - line:364 - INFO| [+] AGX API is running [2022-09-15 10:28:48.547242]
2022-09-15 10:28:48,657 - maincontroller.py - line:364 - INFO| [+] AGX API is running [2022-09-15 10:28:48.657245]
2022-09-15 10:28:48,892 - maincontroller.py - line:364 - INFO| [+] AGX API is running [2022-09-15 10:28:48.892245]
2022-09-15 10:28:48,919 - maincontroller.py - line:364 - INFO| [+] AGX API is running [2022-09-15 10:28:48.919245]
2022-09-15 10:28:49,041 - maincontroller.py - line:364 - INFO| [+] AGX API is running [2022-09-15 10:28:49.041243]
2022-09-15 10:28:49,273 - maincontroller.py - line:364 - INFO| [+] AGX API is running [2022-09-15 10:28:49.273249]
2022-09-15 10:28:49,346 - maincontroller.py - line:364 - INFO| [+] AGX API is running [2022-09-15 10:28:49.346240]
2022-09-15 10:28:49,624 - detect.py - line:121 - INFO| 
2022-09-15 10:28:49,663 - timeTools.py - line:6 - INFO| 结束时间 2022-09-15 10:28:49.663246
2022-09-15 10:28:50,845 - readImageTools.py - line:45 - INFO| (3000, 4000, 3)
2022-09-15 10:28:51,576 - readImageTools.py - line:45 - INFO| (3000, 4000, 3)
2022-09-15 10:28:52,267 - timeTools.py - line:6 - INFO| 图片分析 -- 开始执行base64->rgb数组 2022-09-15 10:28:52.267780
2022-09-15 10:28:52,813 - timeTools.py - line:6 - INFO| 图片分析 -- 开始执行 uint8  2022-09-15 10:28:52.813773
2022-09-15 10:28:52,814 - timeTools.py - line:6 - INFO| 图片分析 --  开始执行差分运算  2022-09-15 10:28:52.814773
2022-09-15 10:29:00,800 - timeTools.py - line:6 - INFO| 图片分析 --  开始执行阈值分割  2022-09-15 10:29:00.799787
2022-09-15 10:29:00,813 - timeTools.py - line:6 - INFO| 图片分析 --  开始执行 开运算  2022-09-15 10:29:00.813784
2022-09-15 10:29:05,510 - maincontroller.py - line:364 - INFO| [+] AGX API is running [2022-09-15 10:29:05.510779]
2022-09-15 10:29:05,695 - maincontroller.py - line:364 - INFO| [+] AGX API is running [2022-09-15 10:29:05.695777]
2022-09-15 10:29:05,903 - maincontroller.py - line:364 - INFO| [+] AGX API is running [2022-09-15 10:29:05.902778]
2022-09-15 10:29:06,111 - maincontroller.py - line:364 - INFO| [+] AGX API is running [2022-09-15 10:29:06.110778]
2022-09-15 10:29:06,292 - maincontroller.py - line:364 - INFO| [+] AGX API is running [2022-09-15 10:29:06.292778]
2022-09-15 10:29:06,372 - maincontroller.py - line:364 - INFO| [+] AGX API is running [2022-09-15 10:29:06.372776]
2022-09-15 10:29:06,521 - maincontroller.py - line:364 - INFO| [+] AGX API is running [2022-09-15 10:29:06.521778]
2022-09-15 10:29:06,582 - maincontroller.py - line:364 - INFO| [+] AGX API is running [2022-09-15 10:29:06.582778]
2022-09-15 10:29:06,583 - maincontroller.py - line:364 - INFO| [+] AGX API is running [2022-09-15 10:29:06.583779]
2022-09-15 10:29:07,057 - maincontroller.py - line:364 - INFO| [+] AGX API is running [2022-09-15 10:29:07.057777]
2022-09-15 10:29:07,184 - maincontroller.py - line:364 - INFO| [+] AGX API is running [2022-09-15 10:29:07.184778]
2022-09-15 10:29:07,288 - maincontroller.py - line:364 - INFO| [+] AGX API is running [2022-09-15 10:29:07.288775]
2022-09-15 10:29:07,297 - maincontroller.py - line:364 - INFO| [+] AGX API is running [2022-09-15 10:29:07.297779]
2022-09-15 10:29:07,351 - maincontroller.py - line:364 - INFO| [+] AGX API is running [2022-09-15 10:29:07.351778]
2022-09-15 10:29:07,486 - maincontroller.py - line:364 - INFO| [+] AGX API is running [2022-09-15 10:29:07.486774]
2022-09-15 10:29:07,720 - maincontroller.py - line:364 - INFO| [+] AGX API is running [2022-09-15 10:29:07.720778]
2022-09-15 10:29:08,081 - detect.py - line:121 - INFO| 
2022-09-15 10:29:08,091 - timeTools.py - line:6 - INFO| 结束时间 2022-09-15 10:29:08.090774
2022-09-15 10:29:09,115 - readImageTools.py - line:45 - INFO| (3000, 4000, 3)
2022-09-15 10:29:09,725 - readImageTools.py - line:45 - INFO| (3000, 4000, 3)
2022-09-15 10:29:10,042 - timeTools.py - line:6 - INFO| 图片分析 -- 开始执行base64->rgb数组 2022-09-15 10:29:10.042776
2022-09-15 10:29:10,713 - timeTools.py - line:6 - INFO| 图片分析 -- 开始执行 uint8  2022-09-15 10:29:10.713794
2022-09-15 10:29:10,714 - timeTools.py - line:6 - INFO| 图片分析 --  开始执行差分运算  2022-09-15 10:29:10.714792
2022-09-15 10:29:21,975 - timeTools.py - line:6 - INFO| 图片分析 --  开始执行阈值分割  2022-09-15 10:29:21.975781
2022-09-15 10:29:21,986 - timeTools.py - line:6 - INFO| 图片分析 --  开始执行 开运算  2022-09-15 10:29:21.986784
2022-09-15 10:29:26,750 - maincontroller.py - line:364 - INFO| [+] AGX API is running [2022-09-15 10:29:26.750781]
2022-09-15 10:29:26,975 - maincontroller.py - line:89 - INFO| obj_task
2022-09-15 10:29:26,996 - maincontroller.py - line:364 - INFO| [+] AGX API is running [2022-09-15 10:29:26.996780]
2022-09-15 10:29:27,063 - maincontroller.py - line:364 - INFO| [+] AGX API is running [2022-09-15 10:29:27.063781]
2022-09-15 10:29:27,094 - maincontroller.py - line:364 - INFO| [+] AGX API is running [2022-09-15 10:29:27.094781]
2022-09-15 10:29:27,131 - maincontroller.py - line:364 - INFO| [+] AGX API is running [2022-09-15 10:29:27.131781]
2022-09-15 10:29:27,398 - maincontroller.py - line:364 - INFO| [+] AGX API is running [2022-09-15 10:29:27.398779]
2022-09-15 10:29:27,491 - maincontroller.py - line:364 - INFO| [+] AGX API is running [2022-09-15 10:29:27.491781]
2022-09-15 10:29:27,751 - maincontroller.py - line:364 - INFO| [+] AGX API is running [2022-09-15 10:29:27.751780]
2022-09-15 10:29:27,778 - maincontroller.py - line:364 - INFO| [+] AGX API is running [2022-09-15 10:29:27.778780]
2022-09-15 10:29:28,051 - maincontroller.py - line:364 - INFO| [+] AGX API is running [2022-09-15 10:29:28.051780]
2022-09-15 10:29:28,051 - maincontroller.py - line:364 - INFO| [+] AGX API is running [2022-09-15 10:29:28.051780]
2022-09-15 10:29:28,269 - maincontroller.py - line:364 - INFO| [+] AGX API is running [2022-09-15 10:29:28.269780]
2022-09-15 10:29:28,423 - maincontroller.py - line:364 - INFO| [+] AGX API is running [2022-09-15 10:29:28.423781]
2022-09-15 10:29:28,608 - maincontroller.py - line:364 - INFO| [+] AGX API is running [2022-09-15 10:29:28.608780]
2022-09-15 10:29:28,909 - maincontroller.py - line:364 - INFO| [+] AGX API is running [2022-09-15 10:29:28.909793]
2022-09-15 10:29:29,062 - detect.py - line:121 - INFO| 
2022-09-15 10:29:29,069 - timeTools.py - line:6 - INFO| 结束时间 2022-09-15 10:29:29.069786
2022-09-15 10:29:30,598 - maincontroller.py - line:364 - INFO| [+] AGX API is running [2022-09-15 10:29:30.598783]
2022-09-15 10:29:54,447 - maincontroller.py - line:89 - INFO| obj_task
2022-09-15 10:30:08,225 - maincontroller.py - line:89 - INFO| obj_task
2022-09-15 10:32:31,709 - maincontroller.py - line:89 - INFO| obj_task
2022-09-15 10:32:31,828 - maincontroller.py - line:103 - ERROR| 文件夹图片分析异常:Traceback (most recent call last):
  File "D:\Python38\lib\site-packages\sqlalchemy\engine\base.py", line 1205, in _execute_context
    context = constructor(dialect, self, conn, *args)
  File "D:\Python38\lib\site-packages\sqlalchemy\engine\default.py", line 806, in _init_compiled
    self.cursor = self.create_cursor()
  File "D:\Python38\lib\site-packages\sqlalchemy\engine\default.py", line 1162, in create_cursor
    return self._dbapi_connection.cursor()
  File "D:\Python38\lib\site-packages\sqlalchemy\pool\base.py", line 1000, in cursor
    return self.connection.cursor(*args, **kwargs)
  File "D:\Python38\lib\site-packages\mysql\connector\connection.py", line 809, in cursor
    raise errors.OperationalError("MySQL Connection not available.")
mysql.connector.errors.OperationalError: MySQL Connection not available.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\DJI-Runway-Inspection\DJI-Runway-Inspection\server\maincontroller.py", line 90, in img_for_task
    for re_i in obj_task:
  File "D:\Python38\lib\site-packages\sqlalchemy\orm\query.py", line 3503, in __iter__
    return self._execute_and_instances(context)
  File "D:\Python38\lib\site-packages\sqlalchemy\orm\query.py", line 3528, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "D:\Python38\lib\site-packages\sqlalchemy\engine\base.py", line 1014, in execute
    return meth(self, multiparams, params)
  File "D:\Python38\lib\site-packages\sqlalchemy\sql\elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "D:\Python38\lib\site-packages\sqlalchemy\engine\base.py", line 1127, in _execute_clauseelement
    ret = self._execute_context(
  File "D:\Python38\lib\site-packages\sqlalchemy\engine\base.py", line 1207, in _execute_context
    self._handle_dbapi_exception(
  File "D:\Python38\lib\site-packages\sqlalchemy\engine\base.py", line 1511, in _handle_dbapi_exception
    util.raise_(
  File "D:\Python38\lib\site-packages\sqlalchemy\util\compat.py", line 178, in raise_
    raise exception
  File "D:\Python38\lib\site-packages\sqlalchemy\engine\base.py", line 1205, in _execute_context
    context = constructor(dialect, self, conn, *args)
  File "D:\Python38\lib\site-packages\sqlalchemy\engine\default.py", line 806, in _init_compiled
    self.cursor = self.create_cursor()
  File "D:\Python38\lib\site-packages\sqlalchemy\engine\default.py", line 1162, in create_cursor
    return self._dbapi_connection.cursor()
  File "D:\Python38\lib\site-packages\sqlalchemy\pool\base.py", line 1000, in cursor
    return self.connection.cursor(*args, **kwargs)
  File "D:\Python38\lib\site-packages\mysql\connector\connection.py", line 809, in cursor
    raise errors.OperationalError("MySQL Connection not available.")
sqlalchemy.exc.OperationalError: (mysql.connector.errors.OperationalError) MySQL Connection not available.
[SQL: SELECT tb_img.id AS tb_img_id, tb_img.img_name AS tb_img_img_name, tb_img.img_url AS tb_img_img_url, tb_img.is_analysis AS tb_img_is_analysis, tb_img.task_id AS tb_img_task_id, tb_img.ceate_time AS tb_img_ceate_time 
FROM tb_img 
WHERE tb_img.task_id = %(task_id_1)s]
[parameters: [immutabledict({})]]
(Background on this error at: http://sqlalche.me/e/13/e3q8)
行数:90
2022-09-15 10:33:05,289 - maincontroller.py - line:321 - INFO| image_url: http://124.89.8.210:3006/images/write_imgs/DJI_202209150954_072_Test-Group-One/DJI_20220915103302_0016_W.JPG
2022-09-15 10:33:05,327 - maincontroller.py - line:342 - INFO| 开始向图片表插入数据
2022-09-15 10:33:05,929 - maincontroller.py - line:89 - INFO| obj_task
2022-09-15 10:33:06,639 - maincontroller.py - line:321 - INFO| image_url: http://124.89.8.210:3006/images/write_imgs/DJI_202209150954_072_Test-Group-One/DJI_20220915103303_0017_W.JPG
2022-09-15 10:33:06,658 - maincontroller.py - line:342 - INFO| 开始向图片表插入数据
2022-09-15 10:33:08,389 - maincontroller.py - line:89 - INFO| obj_task
2022-09-15 10:33:11,738 - maincontroller.py - line:89 - INFO| obj_task
2022-09-15 10:33:17,225 - maincontroller.py - line:89 - INFO| obj_task
2022-09-15 10:33:23,598 - maincontroller.py - line:89 - INFO| obj_task
2022-09-15 10:33:37,998 - maincontroller.py - line:89 - INFO| obj_task
2022-09-15 10:34:00,600 - maincontroller.py - line:89 - INFO| obj_task
2022-09-15 10:34:09,315 - maincontroller.py - line:89 - INFO| obj_task
2022-09-15 10:38:30,268 - maincontroller.py - line:89 - INFO| obj_task
2022-09-15 10:38:44,178 - maincontroller.py - line:89 - INFO| obj_task
2022-09-15 10:40:30,306 - maincontroller.py - line:89 - INFO| obj_task
2022-09-15 10:43:15,134 - maincontroller.py - line:89 - INFO| obj_task
2022-09-15 10:43:20,109 - maincontroller.py - line:89 - INFO| obj_task
2022-09-15 10:47:13,089 - maincontroller.py - line:364 - INFO| [+] AGX API is running [2022-09-15 10:47:13.089983]
2022-09-15 10:50:07,566 - maincontroller.py - line:339 - INFO| [+] AGX API is running [2022-09-15 10:50:07.566821]
2022-09-15 10:50:36,554 - maincontroller.py - line:89 - INFO| obj_task
2022-09-15 10:50:44,276 - maincontroller.py - line:89 - INFO| obj_task
2022-09-15 10:51:19,406 - maincontroller.py - line:339 - INFO| [+] AGX API is running [2022-09-15 10:51:19.406455]
2022-09-15 11:16:31,209 - maincontroller.py - line:89 - INFO| obj_task
2022-09-15 11:17:20,615 - maincontroller.py - line:89 - INFO| obj_task
2022-09-15 11:17:35,687 - maincontroller.py - line:89 - INFO| obj_task
2022-09-15 11:17:38,936 - maincontroller.py - line:89 - INFO| obj_task
2022-09-15 11:18:51,233 - maincontroller.py - line:89 - INFO| obj_task
2022-09-15 11:19:29,031 - maincontroller.py - line:89 - INFO| obj_task
2022-09-15 11:23:13,189 - maincontroller.py - line:89 - INFO| obj_task
2022-09-15 11:23:30,159 - maincontroller.py - line:89 - INFO| obj_task
2022-09-15 11:23:41,007 - maincontroller.py - line:89 - INFO| obj_task
2022-09-15 11:23:45,091 - maincontroller.py - line:89 - INFO| obj_task
2022-09-15 11:46:53,958 - maincontroller.py - line:89 - INFO| obj_task
2022-09-15 13:50:12,941 - maincontroller.py - line:89 - INFO| obj_task
2022-09-15 13:53:08,918 - maincontroller.py - line:89 - INFO| obj_task
2022-09-15 16:01:58,601 - maincontroller.py - line:89 - INFO| obj_task
2022-09-15 16:11:51,594 - maincontroller.py - line:89 - INFO| obj_task
2022-09-15 16:13:20,567 - maincontroller.py - line:89 - INFO| obj_task
2022-09-15 16:14:40,436 - maincontroller.py - line:89 - INFO| obj_task
2022-09-15 16:18:56,117 - maincontroller.py - line:89 - INFO| obj_task
2022-09-15 16:19:11,894 - maincontroller.py - line:89 - INFO| obj_task
2022-09-15 16:20:58,614 - maincontroller.py - line:89 - INFO| obj_task
2022-09-15 16:48:13,746 - maincontroller.py - line:89 - INFO| obj_task
2022-09-15 16:50:42,192 - maincontroller.py - line:89 - INFO| obj_task
2022-09-15 16:50:58,305 - maincontroller.py - line:89 - INFO| obj_task
2022-09-15 16:51:09,894 - maincontroller.py - line:89 - INFO| obj_task
2022-09-15 16:53:51,744 - maincontroller.py - line:339 - INFO| [+] AGX API is running [2022-09-15 16:53:51.744141]
2022-09-15 16:54:56,137 - maincontroller.py - line:286 - INFO| 开始向航线数据表插入数据
2022-09-15 16:54:56,158 - maincontroller.py - line:290 - INFO| 数据插入成功
2022-09-15 16:54:56,159 - maincontroller.py - line:296 - INFO| image_url: http://124.89.8.210:3006/images/write_imgs/DJI_202209151653_073_Test-Group-One/DJI_20220915165450_0001_W.JPG
2022-09-15 16:54:56,167 - maincontroller.py - line:302 - INFO| 开始向任务数据表插入数据
2022-09-15 16:54:56,201 - maincontroller.py - line:308 - INFO| 任务数据插入成功
2022-09-15 16:54:56,209 - maincontroller.py - line:317 - INFO| 开始向图片表插入数据
2022-09-15 16:55:01,179 - maincontroller.py - line:296 - INFO| image_url: http://124.89.8.210:3006/images/write_imgs/DJI_202209151653_073_Test-Group-One/DJI_20220915165455_0002_W.JPG
2022-09-15 16:55:01,191 - maincontroller.py - line:317 - INFO| 开始向图片表插入数据
2022-09-15 16:55:15,468 - maincontroller.py - line:89 - INFO| obj_task: SELECT tb_img.id AS tb_img_id, tb_img.img_name AS tb_img_img_name, tb_img.img_url AS tb_img_img_url, tb_img.is_analysis AS tb_img_is_analysis, tb_img.task_id AS tb_img_task_id, tb_img.ceate_time AS tb_img_ceate_time 
FROM tb_img 
WHERE tb_img.task_id = %(task_id_1)s
2022-09-15 16:55:53,944 - maincontroller.py - line:89 - INFO| obj_task: SELECT tb_img.id AS tb_img_id, tb_img.img_name AS tb_img_img_name, tb_img.img_url AS tb_img_img_url, tb_img.is_analysis AS tb_img_is_analysis, tb_img.task_id AS tb_img_task_id, tb_img.ceate_time AS tb_img_ceate_time 
FROM tb_img 
WHERE tb_img.task_id = %(task_id_1)s
2022-09-15 16:56:15,983 - maincontroller.py - line:89 - INFO| obj_task: SELECT tb_img.id AS tb_img_id, tb_img.img_name AS tb_img_img_name, tb_img.img_url AS tb_img_img_url, tb_img.is_analysis AS tb_img_is_analysis, tb_img.task_id AS tb_img_task_id, tb_img.ceate_time AS tb_img_ceate_time 
FROM tb_img 
WHERE tb_img.task_id = %(task_id_1)s
2022-09-15 16:56:25,543 - maincontroller.py - line:89 - INFO| obj_task: SELECT tb_img.id AS tb_img_id, tb_img.img_name AS tb_img_img_name, tb_img.img_url AS tb_img_img_url, tb_img.is_analysis AS tb_img_is_analysis, tb_img.task_id AS tb_img_task_id, tb_img.ceate_time AS tb_img_ceate_time 
FROM tb_img 
WHERE tb_img.task_id = %(task_id_1)s
2022-09-15 16:58:14,501 - maincontroller.py - line:89 - INFO| obj_task: SELECT tb_img.id AS tb_img_id, tb_img.img_name AS tb_img_img_name, tb_img.img_url AS tb_img_img_url, tb_img.is_analysis AS tb_img_is_analysis, tb_img.task_id AS tb_img_task_id, tb_img.ceate_time AS tb_img_ceate_time 
FROM tb_img 
WHERE tb_img.task_id = %(task_id_1)s
2022-09-15 16:59:11,846 - maincontroller.py - line:338 - INFO| [+] AGX API is running [2022-09-15 16:59:11.846127]
2022-09-15 17:41:17,978 - maincontroller.py - line:295 - INFO| image_url: http://124.89.8.210:3006/images/write_imgs/DJI_202209151738_074_Test-Group-One/DJI_20220915174114_0001_W.JPG
2022-09-15 17:41:17,986 - maincontroller.py - line:301 - INFO| 开始向任务数据表插入数据
2022-09-15 17:41:18,007 - maincontroller.py - line:307 - INFO| 任务数据插入成功
2022-09-15 17:41:18,015 - maincontroller.py - line:316 - INFO| 开始向图片表插入数据
2022-09-15 17:41:20,363 - maincontroller.py - line:295 - INFO| image_url: http://124.89.8.210:3006/images/write_imgs/DJI_202209151738_074_Test-Group-One/DJI_20220915174116_0002_W.JPG
2022-09-15 17:41:20,374 - maincontroller.py - line:316 - INFO| 开始向图片表插入数据
2022-09-15 17:41:23,494 - maincontroller.py - line:295 - INFO| image_url: http://124.89.8.210:3006/images/write_imgs/DJI_202209151738_074_Test-Group-One/DJI_20220915174119_0003_W.JPG
2022-09-15 17:41:23,505 - maincontroller.py - line:316 - INFO| 开始向图片表插入数据
2022-09-15 17:43:55,970 - maincontroller.py - line:190 - INFO| 指定任务为模板成功!
2022-09-15 17:44:09,536 - maincontroller.py - line:207 - INFO| type(task_id): <class 'int'>
2022-09-15 17:44:09,547 - maincontroller.py - line:219 - INFO| 开始修改对比状态
2022-09-15 17:44:09,553 - maincontroller.py - line:222 - INFO| 对比状态修改成功
2022-09-15 17:44:09,573 - maincontroller.py - line:232 - INFO| 对比状态修改成功
2022-09-15 17:44:10,486 - readImageTools.py - line:45 - INFO| (3888, 5184, 3)
2022-09-15 17:44:12,879 - readImageTools.py - line:45 - INFO| (3888, 5184, 3)
2022-09-15 17:44:13,598 - timeTools.py - line:6 - INFO| 图片分析 -- 开始执行base64->rgb数组 2022-09-15 17:44:13.598758
2022-09-15 17:44:14,677 - timeTools.py - line:6 - INFO| 图片分析 -- 开始执行 uint8  2022-09-15 17:44:14.677783
2022-09-15 17:44:14,677 - timeTools.py - line:6 - INFO| 图片分析 --  开始执行差分运算  2022-09-15 17:44:14.677783
2022-09-15 17:44:29,479 - timeTools.py - line:6 - INFO| 图片分析 --  开始执行阈值分割  2022-09-15 17:44:29.479941
2022-09-15 17:44:29,504 - timeTools.py - line:6 - INFO| 图片分析 --  开始执行 开运算  2022-09-15 17:44:29.504941
2022-09-15 17:44:33,489 - maincontroller.py - line:337 - INFO| [+] AGX API is running [2022-09-15 17:44:33.489969]
2022-09-15 17:44:35,184 - maincontroller.py - line:337 - INFO| [+] AGX API is running [2022-09-15 17:44:35.184985]
2022-09-15 17:44:35,478 - maincontroller.py - line:337 - INFO| [+] AGX API is running [2022-09-15 17:44:35.478989]
2022-09-15 17:44:35,631 - maincontroller.py - line:337 - INFO| [+] AGX API is running [2022-09-15 17:44:35.631989]
2022-09-15 17:44:35,772 - maincontroller.py - line:337 - INFO| [+] AGX API is running [2022-09-15 17:44:35.772992]
2022-09-15 17:44:35,773 - maincontroller.py - line:337 - INFO| [+] AGX API is running [2022-09-15 17:44:35.773992]
2022-09-15 17:44:36,005 - maincontroller.py - line:337 - INFO| [+] AGX API is running [2022-09-15 17:44:36.005993]
2022-09-15 17:44:36,138 - maincontroller.py - line:337 - INFO| [+] AGX API is running [2022-09-15 17:44:36.138991]
2022-09-15 17:44:36,354 - maincontroller.py - line:337 - INFO| [+] AGX API is running [2022-09-15 17:44:36.354997]
2022-09-15 17:44:36,482 - maincontroller.py - line:337 - INFO| [+] AGX API is running [2022-09-15 17:44:36.482994]
2022-09-15 17:44:36,546 - maincontroller.py - line:337 - INFO| [+] AGX API is running [2022-09-15 17:44:36.546000]
2022-09-15 17:44:36,767 - maincontroller.py - line:337 - INFO| [+] AGX API is running [2022-09-15 17:44:36.768000]
2022-09-15 17:44:37,558 - maincontroller.py - line:337 - INFO| [+] AGX API is running [2022-09-15 17:44:37.558011]
2022-09-15 17:44:37,885 - maincontroller.py - line:337 - INFO| [+] AGX API is running [2022-09-15 17:44:37.885019]
2022-09-15 17:44:38,128 - maincontroller.py - line:337 - INFO| [+] AGX API is running [2022-09-15 17:44:38.128030]
2022-09-15 17:44:38,216 - detect.py - line:121 - INFO| 
2022-09-15 17:44:38,224 - timeTools.py - line:6 - INFO| 结束时间 2022-09-15 17:44:38.224018
2022-09-15 17:44:38,982 - maincontroller.py - line:337 - INFO| [+] AGX API is running [2022-09-15 17:44:38.982026]
2022-09-15 17:44:39,735 - readImageTools.py - line:45 - INFO| (3888, 5184, 3)
2022-09-15 17:44:41,073 - readImageTools.py - line:45 - INFO| (3888, 5184, 3)
2022-09-15 17:44:41,637 - timeTools.py - line:6 - INFO| 图片分析 -- 开始执行base64->rgb数组 2022-09-15 17:44:41.637052
2022-09-15 17:44:43,190 - timeTools.py - line:6 - INFO| 图片分析 -- 开始执行 uint8  2022-09-15 17:44:43.190084
2022-09-15 17:44:43,191 - timeTools.py - line:6 - INFO| 图片分析 --  开始执行差分运算  2022-09-15 17:44:43.191092
2022-09-15 17:44:57,869 - timeTools.py - line:6 - INFO| 图片分析 --  开始执行阈值分割  2022-09-15 17:44:57.868227
2022-09-15 17:44:57,886 - timeTools.py - line:6 - INFO| 图片分析 --  开始执行 开运算  2022-09-15 17:44:57.886243
2022-09-15 17:45:01,714 - maincontroller.py - line:337 - INFO| [+] AGX API is running [2022-09-15 17:45:01.714264]
2022-09-15 17:45:03,725 - maincontroller.py - line:337 - INFO| [+] AGX API is running [2022-09-15 17:45:03.725286]
2022-09-15 17:45:03,929 - maincontroller.py - line:337 - INFO| [+] AGX API is running [2022-09-15 17:45:03.929289]
2022-09-15 17:45:04,010 - maincontroller.py - line:337 - INFO| [+] AGX API is running [2022-09-15 17:45:04.010289]
2022-09-15 17:45:04,015 - maincontroller.py - line:337 - INFO| [+] AGX API is running [2022-09-15 17:45:04.015289]
2022-09-15 17:45:04,183 - maincontroller.py - line:337 - INFO| [+] AGX API is running [2022-09-15 17:45:04.183288]
2022-09-15 17:45:04,244 - maincontroller.py - line:337 - INFO| [+] AGX API is running [2022-09-15 17:45:04.244290]
2022-09-15 17:45:04,500 - maincontroller.py - line:337 - INFO| [+] AGX API is running [2022-09-15 17:45:04.500289]
2022-09-15 17:45:04,502 - maincontroller.py - line:337 - INFO| [+] AGX API is running [2022-09-15 17:45:04.502290]
2022-09-15 17:45:04,790 - maincontroller.py - line:337 - INFO| [+] AGX API is running [2022-09-15 17:45:04.789297]
2022-09-15 17:45:04,875 - maincontroller.py - line:337 - INFO| [+] AGX API is running [2022-09-15 17:45:04.875295]
2022-09-15 17:45:05,627 - maincontroller.py - line:337 - INFO| [+] AGX API is running [2022-09-15 17:45:05.627303]
2022-09-15 17:45:05,775 - maincontroller.py - line:337 - INFO| [+] AGX API is running [2022-09-15 17:45:05.775304]
2022-09-15 17:45:06,100 - maincontroller.py - line:337 - INFO| [+] AGX API is running [2022-09-15 17:45:06.099310]
2022-09-15 17:45:06,389 - detect.py - line:121 - INFO| 
2022-09-15 17:45:06,397 - timeTools.py - line:6 - INFO| 结束时间 2022-09-15 17:45:06.397310
2022-09-15 17:45:07,101 - maincontroller.py - line:337 - INFO| [+] AGX API is running [2022-09-15 17:45:07.101325]
2022-09-15 17:45:07,612 - maincontroller.py - line:337 - INFO| [+] AGX API is running [2022-09-15 17:45:07.612327]
2022-09-15 17:45:07,789 - readImageTools.py - line:45 - INFO| (3888, 5184, 3)
2022-09-15 17:45:08,842 - readImageTools.py - line:45 - INFO| (3888, 5184, 3)
2022-09-15 17:45:09,402 - timeTools.py - line:6 - INFO| 图片分析 -- 开始执行base64->rgb数组 2022-09-15 17:45:09.402342
2022-09-15 17:45:10,657 - timeTools.py - line:6 - INFO| 图片分析 -- 开始执行 uint8  2022-09-15 17:45:10.657369
2022-09-15 17:45:10,657 - timeTools.py - line:6 - INFO| 图片分析 --  开始执行差分运算  2022-09-15 17:45:10.657369
2022-09-15 17:45:27,464 - timeTools.py - line:6 - INFO| 图片分析 --  开始执行阈值分割  2022-09-15 17:45:27.464538
2022-09-15 17:45:27,483 - timeTools.py - line:6 - INFO| 图片分析 --  开始执行 开运算  2022-09-15 17:45:27.482544
2022-09-15 17:45:31,921 - maincontroller.py - line:337 - INFO| [+] AGX API is running [2022-09-15 17:45:31.921581]
2022-09-15 17:45:33,103 - maincontroller.py - line:337 - INFO| [+] AGX API is running [2022-09-15 17:45:33.103595]
2022-09-15 17:45:33,292 - maincontroller.py - line:337 - INFO| [+] AGX API is running [2022-09-15 17:45:33.292596]
2022-09-15 17:45:33,310 - maincontroller.py - line:337 - INFO| [+] AGX API is running [2022-09-15 17:45:33.310597]
2022-09-15 17:45:34,085 - maincontroller.py - line:337 - INFO| [+] AGX API is running [2022-09-15 17:45:34.085605]
2022-09-15 17:45:34,255 - maincontroller.py - line:337 - INFO| [+] AGX API is running [2022-09-15 17:45:34.255607]
2022-09-15 17:45:34,345 - maincontroller.py - line:337 - INFO| [+] AGX API is running [2022-09-15 17:45:34.345608]
2022-09-15 17:45:34,536 - maincontroller.py - line:337 - INFO| [+] AGX API is running [2022-09-15 17:45:34.536603]
2022-09-15 17:45:34,622 - maincontroller.py - line:337 - INFO| [+] AGX API is running [2022-09-15 17:45:34.622605]
2022-09-15 17:45:34,803 - maincontroller.py - line:337 - INFO| [+] AGX API is running [2022-09-15 17:45:34.803612]
2022-09-15 17:45:34,972 - maincontroller.py - line:337 - INFO| [+] AGX API is running [2022-09-15 17:45:34.972614]
2022-09-15 17:45:35,021 - maincontroller.py - line:337 - INFO| [+] AGX API is running [2022-09-15 17:45:35.021614]
2022-09-15 17:45:35,177 - maincontroller.py - line:337 - INFO| [+] AGX API is running [2022-09-15 17:45:35.177617]
2022-09-15 17:45:35,245 - maincontroller.py - line:337 - INFO| [+] AGX API is running [2022-09-15 17:45:35.245617]
2022-09-15 17:45:35,514 - maincontroller.py - line:337 - INFO| [+] AGX API is running [2022-09-15 17:45:35.514619]
2022-09-15 17:45:35,702 - maincontroller.py - line:337 - INFO| [+] AGX API is running [2022-09-15 17:45:35.702622]
2022-09-15 17:45:36,425 - detect.py - line:121 - INFO| 
2022-09-15 17:45:36,433 - timeTools.py - line:6 - INFO| 结束时间 2022-09-15 17:45:36.433626
2022-09-15 17:45:37,566 - readImageTools.py - line:45 - INFO| (3888, 5184, 3)
2022-09-15 17:45:38,643 - readImageTools.py - line:45 - INFO| (3888, 5184, 3)
2022-09-15 17:45:40,019 - timeTools.py - line:6 - INFO| 图片分析 -- 开始执行base64->rgb数组 2022-09-15 17:45:40.019687
2022-09-15 17:45:41,587 - timeTools.py - line:6 - INFO| 图片分析 -- 开始执行 uint8  2022-09-15 17:45:41.587696
2022-09-15 17:45:41,588 - timeTools.py - line:6 - INFO| 图片分析 --  开始执行差分运算  2022-09-15 17:45:41.587696
2022-09-15 17:45:55,157 - timeTools.py - line:6 - INFO| 图片分析 --  开始执行阈值分割  2022-09-15 17:45:55.157831
2022-09-15 17:45:55,175 - timeTools.py - line:6 - INFO| 图片分析 --  开始执行 开运算  2022-09-15 17:45:55.175827
2022-09-15 17:45:59,785 - maincontroller.py - line:337 - INFO| [+] AGX API is running [2022-09-15 17:45:59.785875]
2022-09-15 17:46:01,128 - maincontroller.py - line:337 - INFO| [+] AGX API is running [2022-09-15 17:46:01.127888]
2022-09-15 17:46:01,185 - maincontroller.py - line:337 - INFO| [+] AGX API is running [2022-09-15 17:46:01.185890]
2022-09-15 17:46:01,297 - maincontroller.py - line:337 - INFO| [+] AGX API is running [2022-09-15 17:46:01.296891]
2022-09-15 17:46:01,425 - maincontroller.py - line:337 - INFO| [+] AGX API is running [2022-09-15 17:46:01.425892]
2022-09-15 17:46:01,428 - maincontroller.py - line:337 - INFO| [+] AGX API is running [2022-09-15 17:46:01.428893]
2022-09-15 17:46:01,511 - maincontroller.py - line:337 - INFO| [+] AGX API is running [2022-09-15 17:46:01.511892]
2022-09-15 17:46:01,810 - maincontroller.py - line:337 - INFO| [+] AGX API is running [2022-09-15 17:46:01.810896]
2022-09-15 17:46:02,320 - maincontroller.py - line:337 - INFO| [+] AGX API is running [2022-09-15 17:46:02.320901]
2022-09-15 17:46:02,347 - maincontroller.py - line:337 - INFO| [+] AGX API is running [2022-09-15 17:46:02.347897]
2022-09-15 17:46:02,494 - maincontroller.py - line:337 - INFO| [+] AGX API is running [2022-09-15 17:46:02.494903]
2022-09-15 17:46:02,542 - maincontroller.py - line:337 - INFO| [+] AGX API is running [2022-09-15 17:46:02.542905]
2022-09-15 17:46:02,632 - maincontroller.py - line:337 - INFO| [+] AGX API is running [2022-09-15 17:46:02.631900]
2022-09-15 17:46:02,894 - maincontroller.py - line:337 - INFO| [+] AGX API is running [2022-09-15 17:46:02.894907]
2022-09-15 17:46:03,306 - maincontroller.py - line:337 - INFO| [+] AGX API is running [2022-09-15 17:46:03.306912]
2022-09-15 17:46:03,412 - maincontroller.py - line:337 - INFO| [+] AGX API is running [2022-09-15 17:46:03.411913]
2022-09-15 17:46:03,996 - detect.py - line:121 - INFO| 
2022-09-15 17:46:04,004 - timeTools.py - line:6 - INFO| 结束时间 2022-09-15 17:46:04.004916
2022-09-15 17:46:05,058 - readImageTools.py - line:45 - INFO| (3888, 5184, 3)
2022-09-15 17:46:06,129 - readImageTools.py - line:45 - INFO| (3888, 5184, 3)
2022-09-15 17:46:07,296 - timeTools.py - line:6 - INFO| 图片分析 -- 开始执行base64->rgb数组 2022-09-15 17:46:07.296953
2022-09-15 17:46:08,041 - timeTools.py - line:6 - INFO| 图片分析 -- 开始执行 uint8  2022-09-15 17:46:08.041971
2022-09-15 17:46:08,041 - timeTools.py - line:6 - INFO| 图片分析 --  开始执行差分运算  2022-09-15 17:46:08.041971
2022-09-15 17:46:23,228 - timeTools.py - line:6 - INFO| 图片分析 --  开始执行阈值分割  2022-09-15 17:46:23.228125
2022-09-15 17:46:23,245 - timeTools.py - line:6 - INFO| 图片分析 --  开始执行 开运算  2022-09-15 17:46:23.245137
2022-09-15 17:46:26,904 - maincontroller.py - line:337 - INFO| [+] AGX API is running [2022-09-15 17:46:26.904159]
2022-09-15 17:46:29,248 - maincontroller.py - line:337 - INFO| [+] AGX API is running [2022-09-15 17:46:29.248184]
2022-09-15 17:46:29,391 - maincontroller.py - line:337 - INFO| [+] AGX API is running [2022-09-15 17:46:29.391185]
2022-09-15 17:46:29,395 - maincontroller.py - line:337 - INFO| [+] AGX API is running [2022-09-15 17:46:29.395185]
2022-09-15 17:46:29,487 - maincontroller.py - line:337 - INFO| [+] AGX API is running [2022-09-15 17:46:29.487186]
2022-09-15 17:46:29,531 - maincontroller.py - line:337 - INFO| [+] AGX API is running [2022-09-15 17:46:29.531187]
2022-09-15 17:46:29,770 - maincontroller.py - line:337 - INFO| [+] AGX API is running [2022-09-15 17:46:29.770187]
2022-09-15 17:46:29,853 - maincontroller.py - line:337 - INFO| [+] AGX API is running [2022-09-15 17:46:29.852184]
2022-09-15 17:46:29,916 - maincontroller.py - line:337 - INFO| [+] AGX API is running [2022-09-15 17:46:29.916188]
2022-09-15 17:46:30,473 - maincontroller.py - line:337 - INFO| [+] AGX API is running [2022-09-15 17:46:30.472193]
2022-09-15 17:46:30,616 - maincontroller.py - line:337 - INFO| [+] AGX API is running [2022-09-15 17:46:30.616199]
2022-09-15 17:46:30,823 - maincontroller.py - line:337 - INFO| [+] AGX API is running [2022-09-15 17:46:30.823196]
2022-09-15 17:46:31,201 - maincontroller.py - line:337 - INFO| [+] AGX API is running [2022-09-15 17:46:31.201202]
2022-09-15 17:46:31,486 - maincontroller.py - line:337 - INFO| [+] AGX API is running [2022-09-15 17:46:31.486207]
2022-09-15 17:46:31,508 - maincontroller.py - line:337 - INFO| [+] AGX API is running [2022-09-15 17:46:31.508205]
2022-09-15 17:46:31,979 - maincontroller.py - line:337 - INFO| [+] AGX API is running [2022-09-15 17:46:31.979225]
2022-09-15 17:46:32,061 - detect.py - line:121 - INFO| 
2022-09-15 17:46:32,069 - timeTools.py - line:6 - INFO| 结束时间 2022-09-15 17:46:32.069210
2022-09-16 09:30:46,621 - maincontroller.py - line:325 - ERROR| 图片分析异常:Traceback (most recent call last):
  File "D:\Python38\lib\site-packages\werkzeug\wrappers\request.py", line 586, in get_json
    rv = self.json_module.loads(data)
  File "D:\Python38\lib\site-packages\flask\json\__init__.py", line 220, in loads
    return _json.loads(s, **kwargs)
  File "D:\Python38\lib\json\__init__.py", line 370, in loads
    return cls(**kw).decode(s)
  File "D:\Python38\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\Python38\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 2 column 1 (char 3)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\DJI-Runway-Inspection\DJI-Runway-Inspection\server\maincontroller.py", line 264, in download_file
    # 原文件名
  File "D:\Python38\lib\site-packages\werkzeug\wrappers\request.py", line 595, in get_json
    rv = self.on_json_loading_failed(e)
  File "D:\Python38\lib\site-packages\flask\wrappers.py", line 131, in on_json_loading_failed
    raise BadRequest()
werkzeug.exceptions.BadRequest: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
行数:264
2022-09-16 09:31:26,305 - maincontroller.py - line:325 - ERROR| 图片分析异常:Traceback (most recent call last):
  File "D:\Python38\lib\site-packages\werkzeug\wrappers\request.py", line 586, in get_json
    rv = self.json_module.loads(data)
  File "D:\Python38\lib\site-packages\flask\json\__init__.py", line 220, in loads
    return _json.loads(s, **kwargs)
  File "D:\Python38\lib\json\__init__.py", line 370, in loads
    return cls(**kw).decode(s)
  File "D:\Python38\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\Python38\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 2 column 1 (char 3)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\DJI-Runway-Inspection\DJI-Runway-Inspection\server\maincontroller.py", line 264, in download_file
    # 原文件名
  File "D:\Python38\lib\site-packages\werkzeug\wrappers\request.py", line 595, in get_json
    rv = self.on_json_loading_failed(e)
  File "D:\Python38\lib\site-packages\flask\wrappers.py", line 131, in on_json_loading_failed
    raise BadRequest()
werkzeug.exceptions.BadRequest: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
行数:264
2022-09-16 09:48:58,307 - maincontroller.py - line:190 - INFO| 指定任务为模板成功!
2022-09-16 09:48:59,724 - maincontroller.py - line:207 - INFO| type(task_id): <class 'int'>
2022-09-16 09:48:59,735 - maincontroller.py - line:219 - INFO| 开始修改对比状态
2022-09-16 09:48:59,747 - maincontroller.py - line:222 - INFO| 对比状态修改成功
2022-09-16 09:48:59,786 - maincontroller.py - line:232 - INFO| 对比状态修改成功
2022-09-16 09:49:00,493 - readImageTools.py - line:45 - INFO| (3000, 4000, 3)
2022-09-16 09:49:01,929 - readImageTools.py - line:45 - INFO| (3000, 4000, 3)
2022-09-16 09:49:02,273 - timeTools.py - line:6 - INFO| 图片分析 -- 开始执行base64->rgb数组 2022-09-16 09:49:02.273657
2022-09-16 09:49:02,724 - timeTools.py - line:6 - INFO| 图片分析 -- 开始执行 uint8  2022-09-16 09:49:02.724657
2022-09-16 09:49:02,724 - timeTools.py - line:6 - INFO| 图片分析 --  开始执行差分运算  2022-09-16 09:49:02.724657
2022-09-16 09:49:12,162 - timeTools.py - line:6 - INFO| 图片分析 --  开始执行阈值分割  2022-09-16 09:49:12.162792
2022-09-16 09:49:12,179 - timeTools.py - line:6 - INFO| 图片分析 --  开始执行 开运算  2022-09-16 09:49:12.179782
2022-09-16 09:49:25,382 - detect.py - line:121 - INFO| 
2022-09-16 09:49:25,388 - timeTools.py - line:6 - INFO| 结束时间 2022-09-16 09:49:25.388907
2022-09-16 09:49:26,280 - readImageTools.py - line:45 - INFO| (3000, 4000, 3)
2022-09-16 09:49:27,080 - readImageTools.py - line:45 - INFO| (3000, 4000, 3)
2022-09-16 09:49:27,475 - timeTools.py - line:6 - INFO| 图片分析 -- 开始执行base64->rgb数组 2022-09-16 09:49:27.475931
2022-09-16 09:49:28,022 - timeTools.py - line:6 - INFO| 图片分析 -- 开始执行 uint8  2022-09-16 09:49:28.022941
2022-09-16 09:49:28,022 - timeTools.py - line:6 - INFO| 图片分析 --  开始执行差分运算  2022-09-16 09:49:28.022941
2022-09-16 09:49:36,093 - timeTools.py - line:6 - INFO| 图片分析 --  开始执行阈值分割  2022-09-16 09:49:36.093029
2022-09-16 09:49:36,104 - timeTools.py - line:6 - INFO| 图片分析 --  开始执行 开运算  2022-09-16 09:49:36.104035
2022-09-16 09:49:43,769 - detect.py - line:121 - INFO| 
2022-09-16 09:49:43,774 - timeTools.py - line:6 - INFO| 结束时间 2022-09-16 09:49:43.774110
2022-09-16 09:49:44,486 - readImageTools.py - line:45 - INFO| (3000, 4000, 3)
2022-09-16 09:49:45,224 - readImageTools.py - line:45 - INFO| (3000, 4000, 3)
2022-09-16 09:49:45,542 - timeTools.py - line:6 - INFO| 图片分析 -- 开始执行base64->rgb数组 2022-09-16 09:49:45.542129
2022-09-16 09:49:45,972 - timeTools.py - line:6 - INFO| 图片分析 -- 开始执行 uint8  2022-09-16 09:49:45.972149
2022-09-16 09:49:45,973 - timeTools.py - line:6 - INFO| 图片分析 --  开始执行差分运算  2022-09-16 09:49:45.973149
2022-09-16 09:49:54,069 - timeTools.py - line:6 - INFO| 图片分析 --  开始执行阈值分割  2022-09-16 09:49:54.069228
2022-09-16 09:49:54,079 - timeTools.py - line:6 - INFO| 图片分析 --  开始执行 开运算  2022-09-16 09:49:54.079228
2022-09-16 09:50:01,473 - detect.py - line:121 - INFO| 
2022-09-16 09:50:01,478 - timeTools.py - line:6 - INFO| 结束时间 2022-09-16 09:50:01.478305
